### ISSUE TITLE
Unable to run xschem

### ISSUE THREAD

**Issue by yashmithak19** [StefanSchippers/xschem#101]
Hi Team,

I am a 1st time user to xschem. I have followed all the steps for the configuration, make make and install as per the user manual and is successfully completed and the xschem.exe is available in the src folder. However on running the xschem.exe file, the xschem window doesn't open as expected. No error/warning message is generated.

 Could you please help me with this?

Note: In am accessing the LINUX environment and executing the commands using **Cygwin**
Attached are the snapshots for your reference.

![image](https://user-images.githubusercontent.com/126053891/220551979-27d4c47a-4245-4589-b369-b90a520671eb.png)

![image](https://user-images.githubusercontent.com/126053891/220550213-d6f662be-38ce-4687-a360-883436cad945.png)
![image](https://user-images.githubusercontent.com/126053891/220550671-1354845d-008d-4095-a04c-20d0fdcd4b36.png)

**Comment by StefanSchippers** [comment]
Xschem is running (you see the xschem tcl prompt %)and this is good. Xschem uses the xorg server to display graphics (like most unix graphical programs). You need to set up [Cygwin/X](https://x.cygwin.com/docs/ug/setup.html) and verify you can run simple X clients, like xclock, xterm and so on. (My suggestion is to install cygwin packages gvim, xterm and x11-apps). If you get these clients running you will be ok with xschem as well.
I did this some years ago. You can configure the cygwin Xserver to run in rootless /seamless mode, so the x apps look like native windows programs.
https://a.fsdn.com/con/app/proj/xschem/screenshots/xschem_on_windows.png/max/max/1

**Comment by yashmithak19** [comment]
Your suggestion was really helpful. 
I already had the X11 packages installed. However since it was invoked incorrectly the xschem GUI was not working. 
On configuring cygwin Xserver to run in multiwindow mode and then invoking cygwin terminal from the System tool and running the xschem from this terminal worked.

![image](https://user-images.githubusercontent.com/126053891/221111764-1fc235dc-3b74-4441-b98a-4f50c8be15a4.png)

Thank you for the support. really helpful!!
