### ISSUE TITLE
Feature request: Add ability to mark components as (temporarily) disabled

### ISSUE THREAD

**Issue by Woazboat** [StefanSchippers/xschem#103]
It would be nice to have an option + hotkey to mark components of a schematic as disabled or ignored. They should still be present in the schematic and displayed, but ignored for netlisting and simulation. 

Disabled components should have some kind of marking or be displayed as greyed out to indicate their status.

This is already more or less possible by setting the `spice_ignore=true` property, but a hotkey/option and a visual indication would be useful.

**Comment by StefanSchippers** [comment]
I din't see the last paragraph. I think a hotkey + visual marker can easily
be done. Will work on that.

Il Mar 9 Mag 2023, 18:39 Woazboat ***@***.***> ha scritto:

**Comment by StefanSchippers** [comment]
In last xschem commit there is a menu entry `Properties ->Toggle *_ignore attribute on selected instances` that adds/removes the spice_ignore=true attribute from selected symbols (more than 1 can be selected), disabled symbols will be drawn in grey:
![1](https://github.com/StefanSchippers/xschem/assets/69359491/454b0506-815c-4e0c-a680-f97e296bc465)

Disabled symbols can be selected, and doing the above menu entry again will re-enable these devices.

This needs some testing, if you find issues please report.

**Comment by Woazboat** [comment]
That was really fast, thank you! I'll try it out soon when I find the time

**Comment by Woazboat** [comment]
Works pretty well in general, but I've noticed some inconsistencies when toggling the ignore property for multiple instances when they have different ignore values. Sometimes not all selected instances are toggled and the toggled instances vary depending on the ignore value.
![xschem_toggle_ignore_2](https://github.com/StefanSchippers/xschem/assets/8714382/06e8885e-dc4d-4391-a3bd-8d96a2c79571)
![xschem_toggle_ignore_4](https://github.com/StefanSchippers/xschem/assets/8714382/d223147e-5d35-462b-93e3-5769fb48da0e)

**Comment by StefanSchippers** [comment]
Yes i have noticed. This will be fixed soon. Currently xschem looks at one of the selected elements and sets ignore flag on all based on the status of the first. This is a flaw.
