### ISSUE TITLE
Expanded mosfet instance names can be duplicated in the schematic without a warning.

### ISSUE THREAD

**Issue by d-m-bailey** [StefanSchippers/xschem#111]
Expanded mosfet instance names can be duplicated in the schematic without a warning.
mpin_fast[1]_q0 (green) will conflict with the expansion of mpin_fast[1:0]_q0 (magenta).
The spice netlist is valid, because the expanded mpin_fast[1]_q0 has been renamed to mpin_fast[1] (red).

Currently, it is impossible to add a simple instance name that is a duplicate of an existing instance name. Is it possible to extend that check to the expansion of array instances?

<img width="1186" alt="xschem_dup_inst" src="https://github.com/StefanSchippers/xschem/assets/8349634/35fc4782-ff22-4efd-a12f-da58da2b3ce0">

**Comment by StefanSchippers** [comment]
@d-m-bailey after a long time i have addressed this long standing issue.
If you add a component its name will be checked for uniqueness.
the name is expanded to single bits, like V1[1:0] --> V1[1],V1[0]
and every single bit name is checked against all single bit names in the schematic. If there are duplicates the component is renamed, for example V1[3:0] --> V2[3:0] until all bits of the renamed instance are unique w.r.t all bits of all other instances.

![1](https://github.com/StefanSchippers/xschem/assets/69359491/3ddf749c-17ab-4040-b346-1dca4014b462)

**Comment by d-m-bailey** [comment]
Excellent!

**Comment by StefanSchippers** [comment]
I believe this is fixed so closing. Feel free to reopen if any problems found.
