### ISSUE TITLE
Symbol creation from schematic overwrites existing symbol without warning.

### ISSUE THREAD

**Issue by d-m-bailey** [StefanSchippers/xschem#113]
Using the `Symbol` -> `Make symbol from schematic` (or the `a` short cut), creates a new symbol, overwriting an existing symbol without a warning.

A confirmation pop up would be appreciated.

**Comment by StefanSchippers** [comment]
I have added a confitrmation dialog if an existing file is about to be overwritten.
Please test

**Comment by d-m-bailey** [comment]
Looks good! Thanks for the quick fix.
