### ISSUE TITLE
Increase GUI elements in HiDPI displays

### ISSUE THREAD

**Issue by niuniuaba** [StefanSchippers/xschem#115]
Hello,

The GUI elements (buttons, fonts, icons, etc.) are too small in my laptop display for me to read. Is it possible to increase the sizes?

Thanks in advance.

**Comment by StefanSchippers** [comment]
there is a `tk_scaling` variable in the `xschemrc` file.
if you do:
`set tk_scaling 2.0`
all GUI elements will be bigger.
default value for tk_scaling is 1.0, so you can increase or decrease the size.

**Comment by niuniuaba** [comment]
Hello Stefan,

Thank you for quick response. Unfortunately that doesn't work (more precisely, not fully work). I set tk_scaling to 2.0 and it seems only the preview in insert symbol widget changes but almost all others doesn't change at all. I attach some screenshots (left: scaling 1.0; right: scaling 2.0)

![insert_symbol](https://github.com/StefanSchippers/xschem/assets/11435613/74753ca7-413b-41f7-9c5d-e28658d57385)

![edit_properties](https://github.com/StefanSchippers/xschem/assets/11435613/058ed629-35d3-4ec3-ad7c-ba992d01556b)

Best regards.

**Comment by StefanSchippers** [comment]
This is strange. I get this. image shows side by side xschem , the second on the right has tk_scaling set to 2.0
![1](https://github.com/StefanSchippers/xschem/assets/69359491/272b3f3f-ff21-44a4-b758-630bd4424345)

**Comment by StefanSchippers** [comment]
Only the toolbar is not resized, this can be done with some small modifications but only by integer numbers, so it is easy to double/triple but not for fractional quantities.

**Comment by StefanSchippers** [comment]
remember to do `set tk_scaling 2.0` (or any other number)  in the xschemrc file, so it will be effective before xschem creates widgets.

**Comment by niuniuaba** [comment]
Hi there,

I tested in two PCs one Ubuntu 22.04 another CentOS variant, all in used with Nvidia graphic drivers, GNOME desktop and X11 server (not wayland), and tk_scaling doesn't work in any of the two.
It's quite difficult to track it down so I just configure fonts in xschem.tcl and everything looks great. I don't use the menubar so much and I think we can close this issue.

Best wishes.

**Comment by StefanSchippers** [comment]
Can you please test this small tk program?
put following text in a test.tcl file:
```
tk scaling 3.0
text .a
.a insert 1.0 "Hello, World!"
pack .a
```
then execute the tcl-tk program:
`wish test.tcl`

you will see a text widget with some text in it.
Try to change the first line (`tk scaling 3.0`)
and run again the program. 
Does text size change?

**Comment by niuniuaba** [comment]
Hi Stefan,

Nope, the text size doesn't change no matter what I put tk scaling to.

**Comment by StefanSchippers** [comment]
Ok  this is consistent with xschem on your systems. May be there is a
desktop environment setting that forbids gui elements scsling.
Another possibility is to set a higher DPI setting in the system
configuration. Every system has different ways to do so, so you need to do
some research.

Il Sab 2 Set 2023, 15:05 niuniuaba ***@***.***> ha scritto:

**Comment by StefanSchippers** [comment]
Please try also this:
```
xschem --tcl 'font configure TkDefaultFont -size 16; font configure TkMenuFont -size 16'
```
this will change the default font and menufont .

If this works you can set these two lines in your xschemrc file:

```
font configure TkDefaultFont -size 16
font configure TkMenuFont -size 16
```

Of course change the size to your specific needs.

**Comment by niuniuaba** [comment]
Hi there,
The font configure in xschemrc works. Much more convenient than modifying xschem.tcl file. Thank you.
