### ISSUE TITLE
Combine netlisting and edit_netlist in a single button

### ISSUE THREAD

**Issue by niuniuaba** [StefanSchippers/xschem#117]
Hi there,

When I do simulations I always expect netlist editor pops up when netlisting finishes the netlist generation so I can take a look before the simulation.
I know I can invoke netlist editor from menu but I am wondering if it is possible to combine these two actions to the netlisting menubutton. In shell (bash, for example) there is something like netlisting && edit_netlist and I think there must be something familiar in Tcl script. This behavior could be annoying to others so I am asking if it's possible to do it on my side.

Best wishes

**Comment by StefanSchippers** [comment]
There are two options. 
If you enable the option "`Show netlist win`"  in the Options menu a window will pop up with the netlist after netlisting. You can edit and save the file if you wish.
![2](https://github.com/StefanSchippers/xschem/assets/69359491/38c8be2a-3965-43ea-9d5f-4612b16b0812)

If you want to use the configured editor for xschem then you need to combine the following two commands:
xschem netlist
edit_netlist [xschem get netlist_name fallback]
You can do this by instantiating a launcher and defining this attribute in it:
`tclcommand="xschem netlist; edit_netlist [xschem get netlist_name fallback]"`

![1](https://github.com/StefanSchippers/xschem/assets/69359491/2fe1f1a6-adcc-4f1a-83f4-5b62fed90dde)

When you do a ctrl-left mouse button click on it a netlist is produced and editor is started:
![3](https://github.com/StefanSchippers/xschem/assets/69359491/cdbc4727-9c95-4b51-b9e0-db9d98b8da5f)

**Comment by StefanSchippers** [comment]
There is a third option: redefine the "`Netlist`" button command:
at the xschem prompt:
```
.menubar.netlist configure -command {xschem netlist -erc; edit_netlist [xschem get netlist_name fallback]}
```
If your xschem is recent you can add this in your xschemrc file:
```
###########################################################################
#### TCL COMMANDS TO BE EXECUTED AFTER COMPLETING STARTUP
###########################################################################
set postinit_commands {
   .menubar.netlist configure -command {xschem netlist -erc; edit_netlist [xschem get netlist_name fallback]}
}
```

**Comment by niuniuaba** [comment]
Wow, what a quick response!
I prefer the last option because I use gvim as netlist editor and it's quite flexible to maintain a local xschemrc file.

Thank you and best wishes.
