### ISSUE TITLE
Crash when using command line option --tcl

### ISSUE THREAD

**Issue by martinjankoehler** [StefanSchippers/xschem#120]
Hey @StefanSchippers 

```
 1018 : xschem --tcl "xschem set format lvs_format"
Segmentation fault (core dumped)
```

IMO even if I should have used `--command`, it should not crash but rather log an error message, perhaps with a hint.

**Comment by StefanSchippers** [comment]
Thank you I will report the error instead of crashing. The correct command is:
`xschem --command "xschem set format lvs_format"`
since --tcl executes the tcl code before xschem has created the xschem extension tcl command.

WIll fix asap and return an error message

**Comment by StefanSchippers** [comment]
It is now fixed. the following output is generated:

```
schippes@asus:~$ xschem --tcl 'xschem set format lvs_format'
tcleval(): evaluation of script: xschem set format lvs_format failed
         : Not available in this context. If using --tcl consider using --command
xschem [~] 
```

**Comment by StefanSchippers** [comment]
looks this is fixed. Fell free to reopen if you find issues.
