### ISSUE TITLE
question about ZOOMing

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#121]
if i zoom out and then zoom in, without moving the mouse in between, i dont come to the same section back. is this intended or some problem?

![1](https://github.com/StefanSchippers/xschem/assets/120017377/b17c9057-1a9d-4ec1-aa1a-9387fa2f84c7)
![2](https://github.com/StefanSchippers/xschem/assets/120017377/dda926fd-e581-4758-acea-f8a4ac3aa95f)
![3](https://github.com/StefanSchippers/xschem/assets/120017377/fad480b2-d617-453d-94f8-8687e6d33be4)

**Comment by StefanSchippers** [comment]
Yes this is intended. However behaviour can be changed in xschemrc: 
uncomment and set following variable to 1:


#### if set to 0, when zooming out allow the viewport do drift toward 
the mouse position,
#### allowing to move away by zooming / unzooming with mouse wheel
#### default setting: 0
# set unzoom_nodrift 0

**Comment by olisnr** [comment]
Xschem is Xtrem: most ideas are already implemented!

thanks a lot!
