### ISSUE TITLE
most of the times i use cntr-mouse-drag to select

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#122]
is there a possibility to swap the cntr-mouse-drag select with the mouse-drag? i searched in the xschemrc but dident found anything.

if not, i can try to do this. the line in select.c:1314 cold make an XOR whit a variable defined in xinit.h and set in options.c. would be this the way?

**Comment by StefanSchippers** [comment]
I have done the change in callback.s, in these lines:

```
     BEFORE                                         AFTER
===============================================================================================
     if(state & ControlMask) {                     if(state & ControlMask) {
       tclsetvar("enable_stretch", "1");             int es = tclgetboolvar("enable_stretch");
                                                     tclsetboolvar("enable_stretch", !es);
       select_rect(END,-1);                          select_rect(END,-1);
       tclsetvar("enable_stretch", "0");             tclsetboolvar("enable_stretch", es);
       break;                                        break;
     } else {                                      } else {

```

so control-drag will flip `enable_stretch` instead of setting it to 1.
The initial state can be already set with `Options->Enable stretch`
This way control-drag and drag can be swapped. Thank you for the hint.

**Comment by olisnr** [comment]
thats great. thanks!

**Comment by olisnr** [comment]
wouldnt it be good to also implement this logic to the cntr-m vs m command? because if im in the drag-wires-mode, then i have the connections saved when i move a rectangle selected part, but not a per click selected part.

if the cntr-m would be standard for the "enable stretch" mode, then both selection types would save the wireing. what do You think?

**Comment by StefanSchippers** [comment]
Yes this makes very sense. Will do that soon.

**Comment by olisnr** [comment]
wouldnt be the "auto join/trim enable" be better in the option menue? near the "enable stretch"?

**Comment by olisnr** [comment]
what does the tools "remember last command"?

**Comment by StefanSchippers** [comment]
Please update xschem

- the m and ctrl-m commands are swapped if `enable stretch` is checked.
- `Remember last command` menu entry renamed to `Persistet wire/line place command`. see video clip for explanation.
- Auto join/trim wires moved to Options menu.

https://github.com/StefanSchippers/xschem/assets/69359491/f0d9a2c0-6b96-48d7-9c30-bfb3bf37e073

**Comment by StefanSchippers** [comment]
I can move it to options, but something must get out of options as it gets too long

the two variables for xschemrc are:  `persistent_command` and `enable_stretch`

**Comment by StefanSchippers** [comment]
ok, done:

"Persistet wire/line place command" goes to Options, 
"Show net names on symbol pins" goes to Symbol, 
"Show netlist after netlist command" goes to Simulation

**Comment by olisnr** [comment]
i think there is something broken now:

selecting
![s1](https://github.com/StefanSchippers/xschem/assets/120017377/409c0e71-5a18-4d3f-90c0-f6b32ed80171)
after pressing "m" a 2nd pice of the wire is also selected
![s2](https://github.com/StefanSchippers/xschem/assets/120017377/bc81fd49-5556-4434-bbb2-938a4ae0ddb1)
after moving the wire is broken
![m](https://github.com/StefanSchippers/xschem/assets/120017377/dfa1a972-9ac0-448a-b015-b1891811164b)

**Comment by StefanSchippers** [comment]
Yes, i have reproduced the issue. will investigate asap

**Comment by StefanSchippers** [comment]
Can you please update & test again?

**Comment by olisnr** [comment]
there is a difference in moving if i u
se the cntr-m between clk selection and drag selection:

clk sel :: m
![clk sel m](https://github.com/StefanSchippers/xschem/assets/120017377/ae5f4125-2f71-407d-aba8-01e3f772bc0a)

clk sel :: cntr-m
![clk sel cntr-m](https://github.com/StefanSchippers/xschem/assets/120017377/0b748246-107f-44a1-a8b3-d8b3b809c04f)

drag sel :: m
![rect sel m](https://github.com/StefanSchippers/xschem/assets/120017377/fd647924-783b-46c5-a0b6-281fc58c6c75)

drag sel :: ctrl-m
![rect sel ctrl-m](https://github.com/StefanSchippers/xschem/assets/120017377/29363967-b1ed-44e3-b107-b1d39103db67)

**Comment by olisnr** [comment]
but im not sure if this intended, because, in the case of click i dont select the points of the wire, and in the drag selection i do...

**Comment by olisnr** [comment]
i think in the cntr-m situation, partial selections should be ignored.

**Comment by StefanSchippers** [comment]
yes this is expected. You can always do a ctrl-drag to avoid selecting wire endpoints

**Comment by olisnr** [comment]
ok. then there is only this selection expanding left of the "m" command. 

as example You select a part only, using click or cntr-drag, and then You want to use the non-dragging move command, but You press by mistake only the m, then the selection is expanded, and if You then press cntr-m You get the dragging movement.

**Comment by StefanSchippers** [comment]
If you press the stretch move command (m in your case) some wire terminals are added to current selection before starting the move operation.

You can do an Alt-Click to unselect the partially selected wires.
May be another useful command to add is  "clear all partial selections".

**Comment by olisnr** [comment]
wouldnt it be nicer for the user, if his selection isnt changed? i mean, You do all the things necessary for the movement, and if the command is completed You restore the users selection?

**Comment by StefanSchippers** [comment]
Sorry, please be very precise, i don't understand the question. What are the actions you are thinking of and what is the behavior you expect?

**Comment by olisnr** [comment]
if i select only a part and do a movement (dragging or only moving), after the movement i want to have the same part selected. 
while moving the selection can change or not, but if the movement is done, the same part should be selected like in the beginning.

**Comment by StefanSchippers** [comment]
I don't understand.

Condider this, first

A move command will just move selected objects (_the selection_)
Full selected wires and symbols are moved as a whole.
Partially selected wires will get only the selected endpoint moved.
After the move operation is done all the selection remains the same.

The special "stretch move" command (m in your case) will just add some partial selects on wires that touch selected objects.
after completing the move operation all selections (full or partial) remain unchanged.

Clearing part of the selection before doing a "non stretch move" operation and restoring afterward is a non trivial change
Modifying the move operation to ignore partial selects is also non trivial.

Also in the default configuration:
doing a control-drag does a selection with partial selection of wires that are not completely inside the selection rectangle.
a following m command moves the seleced set, so partially selected wires will be stretched.
The above command sequences can not be changed since there are too many users that are now used to this.

Also moving some objects away without stretching the attached nets and leaving these partially selected nets selected after the move is a very dangerous situation, see image.
![1](https://github.com/StefanSchippers/xschem/assets/69359491/86a44d81-34d6-4a48-b250-eacb6bd07493)

**Comment by olisnr** [comment]
its about "The special "stretch move" command (m in your case) **will just add some partial selects** on wires that touch selected objects". 

would it be possible that the "stretch move" saves a copy of the actual selection, the add the partial wires, let the user move the selected around, and after ending the movement or after abort the command, restore the in the beginning copied selection? 

i think You do a part of this anyway. because, You do make a copy of the original part-positions, because You need it for the case if the user aborts the command.

**Comment by olisnr** [comment]
like this:

select r
![select r](https://github.com/StefanSchippers/xschem/assets/120017377/9e4cb9da-3ff9-4417-b6c8-11eeb21f277e)

move r
![move r](https://github.com/StefanSchippers/xschem/assets/120017377/cc3af92c-63f6-4d4a-9853-ed4a250f004b)

place r
![end move r](https://github.com/StefanSchippers/xschem/assets/120017377/b5af96d6-fc05-4ec1-a2df-c4a953c7b816)

**Comment by StefanSchippers** [comment]
I have added the option to unselect these partial wires. The tcl variable is: `unselect_partial_sel_wires` (default setting: not enabled (0) ). If set to 1 it does what you asked, if I understood well. This needs some testing.
There is also an entry in the Options menu that toggles this variable.
Thank you!

https://github.com/StefanSchippers/xschem/assets/69359491/aa27c8c9-9ad0-43a8-be26-6c840fb8ff18

**Comment by olisnr** [comment]
thanks a lot that what i asked for, im happy to test it!

i was trying to find out how to do it my self, but Your work is big and complex and i dont understand how its woks. is there a description how the SW works internally?
