### ISSUE TITLE
flipping multiselection

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#127]
if i select more then one thing and use `alt-f` every thing flips for it self.

is it possible to flip it as group? (and is it possible to flip vertical instead of horizontal or do i need combinations of flipping and rotating?)
![preflip](https://github.com/StefanSchippers/xschem/assets/120017377/f92679c8-5d16-4732-960e-60593d4351ff)
![flipped](https://github.com/StefanSchippers/xschem/assets/120017377/b66f92b6-239a-4f78-a982-8f510971ad86)
![wanted](https://github.com/StefanSchippers/xschem/assets/120017377/300ecf92-4a69-475b-913a-1adb7a308703)

**Comment by StefanSchippers** [comment]
Yes, the commands for flipping  and rotating as a whole the selection are Shift-F and Shift-R respectively.
They are documented in the Help-> Keys menu, but are missing in the Edit menu. WIll add these.
A vertical flip is easy to do as 2 rotations + 1 flip in any order.

After 3.4.4 i will also add a vertical flip command.
See short clip.

https://github.com/StefanSchippers/xschem/assets/69359491/e77e5ecd-e8a6-4c28-9d78-291791701c93

**Comment by olisnr** [comment]
great. thanks a lot!
