### ISSUE TITLE
Configure file error

### ISSUE THREAD

**Issue by ripudamank2** [StefanSchippers/xschem#13]
Hi,
I was trying to configure the xschem but its giving below error
"make: *** No rule to make target 'src//scripts/find_welltype.c', needed by 'src//scripts/find_welltype.o'.  Stop.
./configure: 4: ./configure: not found"

I have install all the packages from below website.
http://repo.hu/projects/xschem/xschem_man/install_xschem.html

Can you please tell how to solve it.

[
![Screenshot from 2021-04-18 11-43-29](https://user-images.githubusercontent.com/8544850/115141268-98159d00-a03b-11eb-9cba-c363df4802e0.png)
](url)

**Comment by StefanSchippers** [comment]
I am investigating. Will let you know asap...

**Comment by StefanSchippers** [comment]
Some missing files have been checked in. Pull updates, should be ok now.
Thanks
