### ISSUE TITLE
question about kissing

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#133]
in older versions, there was a option that auto-connected contacting pins using wires, if dragging them via `ctrl-m` or the option. 
i was trying to get this "connection saving", but couldnt figure out how to do it :)

**Comment by StefanSchippers** [comment]
It is now in Edit -> Move objects adding wires to connected pins. (Shift-M).
There was a variable enabling this. It has been removed since the feature is always available.

**Comment by olisnr** [comment]
great. thanks!
