### ISSUE TITLE
CMOS example crashes if ...

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#137]
... "Switch rawfile" is ctrl-clicked, before running the simulation. it says:

```
ich@P43s:/ALL/DoWN/xschem-master$ xschem
% rename dir (null) to /tmp/xschem_emergencysave_cmos_example_dfdddcbabe failed
EMERGENCY SAVE DIR: /tmp/xschem_emergencysave_cmos_example_dfdddcbabe

FATAL: signal 8
while editing: cmos_example
```

https://github.com/StefanSchippers/xschem/assets/120017377/c26518bb-2072-47e5-97a5-76c8a34e5be4

**Comment by StefanSchippers** [comment]
Thank you, this is now fixed. The switch raw file works if there is at least one file loaded and there was no check for this.

**Comment by StefanSchippers** [comment]
A note. Github tells me the mp4 file can not be played because it is corrupt. However I can download and see them.

**Comment by olisnr** [comment]
does Github tell it or the web-browser? i see nothing. on chromium its working. 

thanks for the demo-fix!

**Comment by StefanSchippers** [comment]
I see this on Firefox. Not sure if it is a browser or github issue. I think it is more a browser thing.
![1](https://github.com/StefanSchippers/xschem/assets/69359491/3f925e32-fa63-4dd0-9883-9a5b5eaeb86f)

**Comment by olisnr** [comment]
funny in my firefox version it also dont work... but in chromium it does
