### ISSUE TITLE
Symbol lines dissapear when selected

### ISSUE THREAD

**Issue by Victor-Main** [StefanSchippers/xschem#139]
I have observed this issue when working with Xschem. Whenever I select a component some of its lines will disappear after being selected . To my current observation this only happens when selecting lines that are not purely horizontal or vertical. For example, the circle present in voltage sources or the zig-zag lines on the resistor will disappear when selecting them. But a capacitor will remain untouched and the straight line that goes through the voltage source will also remain in place

For example with this simple low pass filter
![Resistor OK](https://github.com/StefanSchippers/xschem/assets/149525908/8805a3d4-fd83-40b1-883b-5a226e74e4a1)
I select the resistor
![Resistor Selected](https://github.com/StefanSchippers/xschem/assets/149525908/0d39f0b7-bd66-45f7-8158-ef34f221cd56)
But upon unselecting it The resistor will disappear
![Resistor Gone](https://github.com/StefanSchippers/xschem/assets/149525908/05a6ea41-ddd9-4010-95ea-5daa233c5482)
And here is the same example but with a voltage source (the one above)
![voltage source example](https://github.com/StefanSchippers/xschem/assets/149525908/b2cb9117-e0a1-4035-9636-6c67122f8a9b)

It is worth noting that updating the display will solve the issue. So moving the Xschem window, panning the view, or zooming in or out will once again redraw the component without issue.

I am using Xschem V3.4.5 and I have been able to observe this issue both in an ArchLinux and a Debian distro.

**Comment by olisnr** [comment]
thats likley a GPU-driver problem. try the menue `option / Fix for GPUs with broken tiled fill`

**Comment by Victor-Main** [comment]
Thank You. It did indeed fix the issue.

**Comment by StefanSchippers** [comment]
I have now made the "fix" the default drawing method in xschem.
