### ISSUE TITLE
Installing ngspice _xschem and skywater130

### ISSUE THREAD

**Issue by Prabha1010** [StefanSchippers/xschem#140]
I am getting this error which applying patch in Latest directory
<img width="956" alt="image" src="https://github.com/StefanSchippers/xschem/assets/61615252/2d50542a-6cf1-4009-9d42-c1dbed00a849">

**Comment by Prabha1010** [comment]
And i get two different files listed one with.rej and another . acc

<img width="778" alt="image" src="https://github.com/StefanSchippers/xschem/assets/61615252/72557f44-1be0-48d4-8311-acc168f87a6c">

**Comment by Prabha1010** [comment]
I also see that paths are not same in xschemrc file

<img width="741" alt="image" src="https://github.com/StefanSchippers/xschem/assets/61615252/3fb47d9c-6657-47b4-87cf-31872e87c7f8">

**Comment by Prabha1010** [comment]
And my xschem window has these layers which is entirely different from what your video says. Is it coz of earlier errors in installation?
<img width="384" alt="image" src="https://github.com/StefanSchippers/xschem/assets/61615252/ff83329b-00e8-47ff-9526-5a468a99b155">

**Comment by StefanSchippers** [comment]
You followed a very old video. Please do the steps explained [here](https://xschem.sourceforge.io/stefan/xschem_man/tutorial_xschem_sky130.html) to install (in this order) magic, ngspice, open_pdks. For xschem follow the instructions [here](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).

**Comment by Prabha1010** [comment]
Thanks Stefan.
But now when i followed all the steps, i get this 
<img width="844" alt="image" src="https://github.com/StefanSchippers/xschem/assets/61615252/3175679b-14c9-41c5-b568-e982b8940b95">
<img width="822" alt="image" src="https://github.com/StefanSchippers/xschem/assets/61615252/4f18d42d-085e-4e94-8f86-d76905cb8f0e">

**Comment by StefanSchippers** [comment]
This means that you did not install xschem from the sources and you have an old ubuntu xschem installation.
As written in [this](https://xschem.sourceforge.io/stefan/xschem_man/tutorial_xschem_sky130.html) manual page:
**If you install xschem from sources ensure no xschem package is already installed in your linux system. Packaged xschem versions are too old so you should remove the installed package. The command for ubuntu/Debian systems is sudo apt-get remove --purge xschem** 

Then install xschem following [this](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html) manual page.
