### ISSUE TITLE
Changing loaded Libraries breaks alt+L label placement

### ISSUE THREAD

**Issue by Victor-Main** [StefanSchippers/xschem#143]
I have added this two lines into my xschemrc in order to better control which libraries are loaded

```
set XSCHEM_LIBRARY_PATH :/usr/local/share/xschem/xschem_library/devices/
append XSCHEM_LIBRARY_PATH :/home/victor/.xschem/xschem_library/
```

However, Upon doing so and loading Xschem again attempting to create a label with alt+L it will not load the symbol. It attempts to load an ab_pin.sym symbol in the /home/victor forlder. However, if I allow the default libraries to be loaded  ALT+L will correctly load the lab_wire.sym present in the devices library.

![label error](https://github.com/StefanSchippers/xschem/assets/149525908/24f50555-c905-43a9-865a-acde0c64d13e)

I want to mention that the devices library is loaded and that I manually can insert a label symbol. However, using the hotkeys is much more efficient

**Comment by StefanSchippers** [comment]
Thank you for reporting. The problem is caused by the trailing `/` in the set `XSCHEM_LIBRARY_PATH .../devices/` line. I will fix that.

**Comment by StefanSchippers** [comment]
Ok this is fixed now. Thank you for reporting!

**Comment by Victor-Main** [comment]
My pleasure. Thanks to you for the quick fix
