### ISSUE TITLE
Spawning second schematic window fails in MacOS

### ISSUE THREAD

**Issue by stefanoaz** [StefanSchippers/xschem#15]
I am running the latest xschem in Mac OS 10.15.7 (Catalina). When I try to spawn a new schematic window from an existing open schematic, using the hotkey "x", the new schematic fails to be generated and the logfile is attached:

[xschemLogFile.txt](https://github.com/StefanSchippers/xschem/files/6473639/xschemLogFile.txt)

**Comment by StefanSchippers** [comment]
Lack of information from MacOS users ( I don't own a MacOS). Please reopen if you face this issue and want to contribute for solution.
