### ISSUE TITLE
Aborted (core dump)

### ISSUE THREAD

**Issue by madeofmemorie** [StefanSchippers/xschem#156]
![17044040406445216416201135475752](https://github.com/StefanSchippers/xschem/assets/155635161/61a12d32-5455-49d2-81cc-5746104bb593)

**Comment by olisnr** [comment]
no tcl found... try  `sudo apt install tcl`

**Comment by StefanSchippers** [comment]
This is the normal exit (!!) of the configuration program if some needed tools / libraries are missing. In this case tcl, tcl-dev, tk, tk-dev packages are missing. See the complete list [here](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).
