### ISSUE TITLE
cannot copy/paste properly in TCL command window

### ISSUE THREAD

**Issue by cnMuggle** [StefanSchippers/xschem#157]
I am using 3.4.5 now from iis-osic. I noticed the copy/paste behavior in xschem is not function correctly and not consistently

I am not able to select the text to copy in the "Tools->Execute TCL command"
![image](https://github.com/StefanSchippers/xschem/assets/10713939/03d1262b-dd87-47cf-be21-c2480a152724)

here is what I am trying to do, to copy this text from this TCL command input and paste it to xschemrc. I cannot copy it either by right click or ctrl+c. 
![image](https://github.com/StefanSchippers/xschem/assets/10713939/6eb09560-67de-4d07-aaa6-c413dde96e64)

If I press mouse middle button. I think depending on when my mouse pointer is located at. something from originally selected is first copy and then paste into the existing text. 
![image](https://github.com/StefanSchippers/xschem/assets/10713939/39fa3768-636c-437b-bff0-3380ac40bac6)

Here is what I get from the Windows paste board:
**_PATH "$XSCHEM_LIBRARY_PATH:/foss/tools/xschem/64ca25b/share/xschem/xschem_library/devices/"**

here is what I get from the Linux paste board. It's something I previously copied from xschem text window.
![image](https://github.com/StefanSchippers/xschem/assets/10713939/85c53854-c68a-419c-8abe-6f2d5604f4cb)

I guess maybe there is no copy/paste for TCL expression input?
In other time, the situation is that when I have copied and want to copy something else, the paste board always keep the existing copied content but it cannot be overwrite by the latest copy content. I think outside of the xschem program, the linux terminal works well. What I copied can be pasted properly. What I new copied will replace the old copy content.

Thanks

**Comment by StefanSchippers** [comment]
Select all the text in the Tools -> execute TCL command dialog box (this is done by going to the first character, press the left mouse button, drag the mouse to the end of the text, releasing the left button and press 'ctrl-c'.

Then open the xschemrc in a text editor and do 'paste' or press middle mouse button or press 'ctrl-v'
Do not close xschem before completing the paste operation because the selection is handled by the application by X11 standards.

**Comment by cnMuggle** [comment]
> Select all the text in the Tools -> execute TCL command dialog box (this is done by going to the first character, press the left mouse button, drag the mouse to the end of the text, releasing the left button and press 'ctrl-c'.
> 
> Then open the xschemrc in a text editor and do 'paste' or press middle mouse button or press 'ctrl-v', depending on the editor. Do not close xschem before completing the paste operation because the selection is handled by the application by X11 standards.

Thanks, Stefan. If you first copy half of the text and paste them somewhere else, then come back to copy the text all and then paste somethwere, I will only see the half text copied. Somehow the behavior of copy/paste is not consistent. 

In this example below, I first copy $XSCHEM_LIBRARY_PATH and then I want to copy "puts $XSCHEM_LIBRARY_PATH"
but I only get $XSCHEM_LIBRARY_PATH pasted.
![image](https://github.com/StefanSchippers/xschem/assets/10713939/48a03d1d-8048-473a-9e4e-659006ce7251)

**Comment by StefanSchippers** [comment]
I think you are using some virtual machine, may be there are some settings to handle sharing selection / clipboard with the host / guest Operating System. I don't see these issues.

**Comment by cnMuggle** [comment]
> I think you are using some virtual machine, may be there are some settings to handle sharing selection / clipboard with the host / guest Operating System. I don't see these issues.

Just confirmed as well. It seems the Windows docker container issue of iss-osic which having xschem.

**Comment by cnMuggle** [comment]
closed as issue related with OS or container
