### ISSUE TITLE
Trouble in installing xshem

### ISSUE THREAD

**Issue by Blue-moon-pix** [StefanSchippers/xschem#158]
When I run the command " ./configure " I get this error
![1](https://github.com/StefanSchippers/xschem/assets/114819520/20aae4ae-e6a6-4aaa-a722-6ea1262afbbf)

**Comment by StefanSchippers** [comment]
You need to install the C compiler (gcc) and all the other packages listed in [this page](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).

**Comment by Blue-moon-pix** [comment]
> You need to install the C compiler (`gcc`), make (`make`)  and all the other packages listed in [this page](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).

For some reasons gcc was not working I reinstalled it and tried the compile command it worked thanks
