### ISSUE TITLE
Help, someone. RED SKY130pdk TT_ models block.

### ISSUE THREAD

**Issue by timibacco** [StefanSchippers/xschem#160]
Hi , can anyone help explain why the tt models block for the sky130 tops is **red** on xschem startup. Red is not a good color. Can someone help out?
This is a screenshot though.
![Screenshot from 2024-02-03 14-05-15](https://github.com/StefanSchippers/xschem/assets/48661125/c6304cf9-d86c-482f-97b0-4182454e5543)

Plus I also get this warning as well.At Xschem's startup as well.
```
Warning: PDK_ROOT env. var. not found or empty, trying to find an open_pdks install
open_pdks installation: using /usr/local/share/pdk
SKYWATER_MODELS: /usr/local/share/pdk/sky130A/libs.tech/ngspice
SKYWATER_STDCELLS: /usr/local/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/spice
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
WARNING: wrong line layer
```

Seems like an ngspice configuration, I guess, but I really don't know what resources to check out anymore.

**Comment by StefanSchippers** [comment]
You have an old xschem version installed on the system.
Remove the old xschem:
sudo apt purge xschem
then install xschem sources from git and build the program. Read the instructions here:
https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html

**Comment by timibacco** [comment]
Thanks very much. Worked like Xschem.
