### ISSUE TITLE
[RFC] bigger preview in insertion menu and file opener

### ISSUE THREAD

**Issue by qpwo** [StefanSchippers/xschem#165]
Would be nice if I could resize the preview in the GUI or xschemrc. I can barely see what's going on in the bigger schematics.

**Comment by qpwo** [comment]
(Stefan said I was allowed to send a flurry of feature requests :D)

**Comment by StefanSchippers** [comment]
The preview window can now be resized in both directions. Please do a test and report in case of issues.
Thank you

https://github.com/StefanSchippers/xschem/assets/69359491/c24aea91-02d4-445b-8daf-7328c3a99c8e

**Comment by qpwo** [comment]
Works perfectly and persists when you open the menu again! Sweet!
