### ISSUE TITLE
[RFC] ctrl-click spice code to run it

### ISSUE THREAD

**Issue by qpwo** [StefanSchippers/xschem#169]
Problem: I want to quickly try different sims. I don't think the editor has a shortcut for commenting(?). No keyboard shortcut for toggle-spice-ignore either I think.

Solution: ctrl-click code symbol to generate netlist and execute it.

Editor shortcut for commenting or keyboard shortcut for toggle-spice-ignore could also solve this.

**Comment by qpwo** [comment]
(Ok that's my last RFC for now!)

**Comment by StefanSchippers** [comment]
There is such command, it is **Properties -> Toggle *_ignore attribute on selected instances**.

You can select multiple instances and after doing the menu command all selected elements will be toggled (ignored / not ignored)
Will look for a free bind key to associate (there is currently no keybind for that).

**Comment by StefanSchippers** [comment]
You can ctrl-click the code symbol to trigger netlist and simulation:
Add this:
`tclcommand="xschem netlist; simulate"`

**Comment by StefanSchippers** [comment]
So if I understood your reauest the sequence is:

- enable the code block (and disable others if any) by selecting and pressing `Shift-T`
- ctrl-click the (now enabled) code block to run the tcldommand attribute as explained above.

If a command block is disabled (spice_ignore=1) you can enable it before generatng a netlist:
`xschem setprop instance COMMANDS spice_ignore 0`
you can then create a netlist:
`xschem netlist`
and finally disable the code block again:
`xschem setprop instance COMMANDS spice_ignore 1`

**Comment by StefanSchippers** [comment]
![3](https://github.com/StefanSchippers/xschem/assets/69359491/f72b6a75-bd0b-4c87-92ca-dd6ebe806455)

**Comment by qpwo** [comment]
Shift-T is perfect! Much appreciated. That tcl recipe is handy too.

**Comment by qpwo** [comment]
TIL that you can put `tclcommand=` on a `code_shown.sym`

**Comment by StefanSchippers** [comment]
You can put that on any symbol to execute the relevant command.
You can also set a `url=....` attribute to open a web page or local document when ctrl-clicking the instance. Xschem will figure out what application to call (browser for http addresses, pdf viewer for pdf files. In cases you need to tell xschem what to use to open the provided url you can add a `program=...` to specify the application.

Do not set both tclcommand and url/program on the same symbol
