### ISSUE TITLE
pip install or conda install -c conda-forge xschem

### ISSUE THREAD

**Issue by joamatab** [StefanSchippers/xschem#170]
As we have enabled [Schematic driven layout](https://gdsfactory.github.io/gplugins/notebooks/20_schematic_driven_layout.html) in [gdsfactory](https://gdsfactory.github.io/gdsfactory/) it would be great to have an extension for xscheme, so that we can automatically create symbols from our PDK Pcells

How could we pip install or conda install -c conda-forge xschem ?

@proppy

**Comment by joamatab** [comment]
I found it [here](https://anaconda.org/litex-hub/xschem)

```
conda install litex-hub::xschem

```
but seems to have some issues to install

![image](https://github.com/StefanSchippers/xschem/assets/4514346/f4f4dfad-5684-4d96-801e-b4f41c14073a)

**Comment by qpwo** [comment]
seems to be working now

**Comment by StefanSchippers** [comment]
Don't know if I have to do something here... closing for now.
