### ISSUE TITLE
enable intuitive mode

### ISSUE THREAD

**Issue by joamatab** [StefanSchippers/xschem#172]
i find xschem looks great, but is hard to get started if you have never used Cadence. For example i end up using Qucs-s because the UI is more intuitive

How could we enable an intutive mode? 

some examples on the intuitive behavior:

- you can move elements by dragging them with the mouse
- you can click on the pins and draw connections 

@proppy

**Comment by StefanSchippers** [comment]
I think these 'intuitive' modes can be added. Will have a look on this.
For complex circuit design one ot the rules is that a circuit can not be changed by messing with the mouse, so randomly clicking and dragging in the circuit drawing area should not change anything. In many environments this is a de-facto rule. However nothing prevents us from using a couple of configure options to enable / disable these editing modes.

**Comment by StefanSchippers** [comment]
I have added a so called "intuitive_interface" option. It can be set in the Options menu or permanently in xschemrc by setting `set intuitive_interface 1`

https://github.com/StefanSchippers/xschem/assets/69359491/a8fb5fa9-a1fe-4ace-9a82-75a05d9de9f1

**Comment by joamatab** [comment]
Looks amazing! it's nice to be able to move the elements without breaking the connectivity. As a new user into schematic editors I was surprised this was not the default behavior

What are the default and new shortcuts?

A few more suggestions:

- [ ] add a help menu button that takes you to the [docs](http://repo.hu/projects/xschem/xschem_man/xschem_man.html)
- [ ] add in the help a cheat-sheet with all the default shortcuts, and the shortcuts for intuitive mode

**Comment by StefanSchippers** [comment]
docs can be reached by going to Help-> About
![1](https://github.com/StefanSchippers/xschem/assets/69359491/2b987dd4-4ab0-4963-b70f-72deb108bcf4)
The key shorcuts are in `Help->Keys`. I wil add some notes for Intuitive mode, however it's just point & click.
![2](https://github.com/StefanSchippers/xschem/assets/69359491/08d218a3-5ce0-42ae-a394-fee3dad6f49f)
