### ISSUE TITLE
Unable to launch Xschem

### ISSUE THREAD

**Issue by Aayushmi26muktui** [StefanSchippers/xschem#173]
Hi,

I am in the last step but when I try to launch xschem,  it does not launch the xschem window and shows this.

![Capture1](https://github.com/StefanSchippers/xschem/assets/144328223/b628b01a-0c8a-49f6-a281-b1e90b386a27)

Can you please help me ? What do you think I should do next ?

**Comment by StefanSchippers** [comment]
Try to run any other linux graphical application, like xterm, xclock, xedit, 
If xschem does not open a window this means no Xserver is running. 
Try to see if DISPLAY variable is defined:
`echo $DISPLAY`
If nothing is returned try to set it up:
export DISPLAY=:0
but likely no Xserver is running.

**Comment by Aayushmi26muktui** [comment]
Yess you are right no Xserver is running. How do it get Xserver running ?

I tried to install Xservers by :

sudo apt-get install xorg
sudo apt-get install openbox

But that does not fix my problem.

![Capture2](https://github.com/StefanSchippers/xschem/assets/144328223/2e485241-bd04-499b-b145-b263699ef36e)

**Comment by StefanSchippers** [comment]
If you are running a WSL linux under windows do some research. I think lot of people are using this setup, but I don't have a windows machine. 

Try this web page.
https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
