### ISSUE TITLE
[RFC] keep focus in search box in Choose Symbol window

### ISSUE THREAD

**Issue by qpwo** [StefanSchippers/xschem#175]
Would be nice if the "File/Search" field was always focused (unless you are typing new dir I suppose)

![image](https://github.com/StefanSchippers/xschem/assets/10591373/6d03105c-08bd-4d0b-92a4-793ceadb9fa9)

(This would mirror behavior in some file explorers.)

Bonus request 1: If you're inserting symbol (rather than opening a file), then filtering to .sym should be the default.

Bonus request 2: The first result in the top-right could always be highlighted, so if you press enter then it's inserted (or the directory is opened)

**Comment by StefanSchippers** [comment]
I have cleaned up the operations in the file chooser dialog box to allow keyboard only operation. See short clip.
https://github.com/StefanSchippers/xschem/assets/69359491/b9db65ea-a36b-412a-8415-3e0c77649949

**Comment by qpwo** [comment]
Beautiful!

**Comment by qpwo** [comment]
I swear it was working for me like your video a second ago, but now the file box is separate from the search box?? File box is focused -- maybe search box is supposed to be? I must have messed something up... 

![image](https://github.com/StefanSchippers/xschem/assets/10591373/4b452963-7130-4f47-9819-19f96f470d0d)

**Comment by StefanSchippers** [comment]
I separated the search pattern box from the file name box. 
So you can keep a search pattern and click files. Having these two things in one box was confusing.
The search box does not get focus with the TAB key, but you can click in it and set a pattern to restrict displayed files.

**Comment by qpwo** [comment]
Personally I use the search box way more often. But I'm sure you have your reasons!

**Comment by qpwo** [comment]
(Maybe you could drop the radio in the bottom left btw?)

**Comment by StefanSchippers** [comment]
I can add the focus to the search when iterating with the TAb key. I thought it was disturbing. I am quite neutral about that :-)

**Comment by StefanSchippers** [comment]
@qpwo I have done the change:
When opening the file load/insert dialog box the search entry is focused and text is selected.
Will also take focus when iterating with the TAB key.
Thank you.
