### ISSUE TITLE
improve color scheme

### ISSUE THREAD

**Issue by joamatab** [StefanSchippers/xschem#178]
When using dark theme the edit simulators are barely readable and can only see the text when hoovering over it
![image](https://github.com/StefanSchippers/xschem/assets/4514346/ab083aa4-cc29-499e-af74-829e24a6bb50)

How about allowing to configure them from a file?

**Comment by StefanSchippers** [comment]
I don't know why that system decides to use white color for text. In 99% of the systems text is black unless changed by the user.
seems a dark theme colorscheme is used.
This is usually screwed up by some Desktop Environment.

**Comment by StefanSchippers** [comment]
@joamatab I have added explicit setting of the following colors:
  option add *foreground black startupFile
  option add *activeforeground black startupFile
  option add *background {#d9d9d9} startupFile
  option add *activebackground {#ececec} startupFile
  option add *disabledforeground {#a3a3a3} startupFile

I will manage to make these options user selectable in xschemrc file.
For now it should avoid white text on light backgound, I hope.

**Comment by StefanSchippers** [comment]
I have added  an option that can be set in xschemrc file:
`set dark_gui_colorscheme 1`
will start xschem with a dark colorscheme, where 
`set dark_gui_colorscheme 0 `
(the default) will use a light colorscheme.

this option affects the widgets, not the drawing area. A separate `dark_colorscheme` i used for the drawing canvas (default: set to 1), so 4 combinations are possible.

It is possible to customize all colors, but the risk of messing up things and having odd combinations is considerable.
![1](https://github.com/StefanSchippers/xschem/assets/69359491/d91f5dd5-f856-493f-b058-540069aaf964)

**Comment by joamatab** [comment]
amazing! thank you Stefan!
