### ISSUE TITLE
export netlist

### ISSUE THREAD

**Issue by joamatab** [StefanSchippers/xschem#179]
I've been playing with this [lidar example](https://github.com/mabrains/gdsfactory-generic-pdk/blob/main/xschem/README.md) and would like to run LVS on it or convert it to YAML for our gdsfactory schematic driven layout flow

how could we export the netlist?

**Comment by StefanSchippers** [comment]
If you mean how to get the spice netlist out of xschem you can run (even as a subprocess from another script)
`xschem schematic.sch -s -n -o . -x -q `
it will generate the netlist in the current directory.
