### ISSUE TITLE
Issue with graph window

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#180]
Hello!
After last update when I try to open graph window, it opens like this:
![image](https://github.com/StefanSchippers/xschem/assets/113975847/3cd5a691-af72-490c-8af6-0ef10caf0c62)
I use KDE Plasma with X11 windows manager.

**Comment by StefanSchippers** [comment]
Can you resize the window and make it bigger?

**Comment by StefanSchippers** [comment]
I have build xschem with tcl-tk 8.6 (the current version on my system) and with tcl-tk 8.4 (released 20 years ago) and it works.
![1](https://github.com/StefanSchippers/xschem/assets/69359491/83b9e8d5-965f-4cba-90cd-dcc5d7b99f60)

**Comment by georgtree** [comment]
Hello, yes it could be resized to work as usual manually.

**Comment by georgtree** [comment]
Also after update I have display issues with Simulation Configuration window
![image](https://github.com/StefanSchippers/xschem/assets/113975847/f041229c-89fd-4e25-85a1-388c6e90b233)

**Comment by StefanSchippers** [comment]
This is fixed in atest. I saw it yesterday.

**Comment by StefanSchippers** [comment]
If the problem with graph dialog box showing up too small persists  I will force an initial size for it. Is that problem repeatable?
Thank you.

**Comment by georgtree** [comment]
On my work machine graph window is ok, will test it again on home machine

**Comment by StefanSchippers** [comment]
Thank you. In the mean time I wanted this dialog box to "remember its size" so if user resizes it the next time it is opened it will use the last size. (in the running session). so I have to add this function anyway.
