### ISSUE TITLE
what's the difference between button load and browser in Edit Properties

### ISSUE THREAD

**Issue by cnMuggle** [StefanSchippers/xschem#182]
Sorry for my stupid questions, but just be curious why we have both Load and Browse button?
![image](https://github.com/StefanSchippers/xschem/assets/10713939/d371ca14-417d-4c58-9e30-bef3858aa9f3)

**Comment by StefanSchippers** [comment]
The Load button will load the content of a file into the below textbox. This is for example used to get a long set of command lines into a code block.
The Del button will erase the textbox
Browse can be used to replace the symbol name shown in the one-line 'Symbol' entry box on the left with a new one.

**Comment by cnMuggle** [comment]
Thanks for the explanation
