### ISSUE TITLE
Ability to change font size globally for all components

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#185]
Hello!
Question - is it possible to set global font size which overrides all component's texts?
Sometimes it is convenient to change text size to remove text and elements overlap  for better readability before export.

Thank you in advance, George.

**Comment by StefanSchippers** [comment]
There is a tcl variable `cairo_font_scale` that does this globally. However it was used only at startup.
I have made a small change. you can now do in the xschem console:
`set cairo_font_scale 0.7; xschem redraw`
to scale all fonts. Default value for cairo_font_scale is 1,0

**Comment by georgtree** [comment]
Great, thank you!
