### ISSUE TITLE
./configure not work while installing xschem

### ISSUE THREAD

**Issue by DucDuyCPD** [StefanSchippers/xschem#187]
hi, i am new, when i install xschem on ubuntu in vitual machine, i have some problem when i run ./configure command

leducduy@leducduy-virtual-machine:~/xschem-src$ ./configure
./configure: 3: make: not found
./configure: 4: ./configure: not found
leducduy@leducduy-virtual-machine:~/xschem-src$ ./configure --prefix=/home/schippes
./configure: 3: make: not found
./configure: 4: ./configure: not found

how can i fix this? thanks

**Comment by StefanSchippers** [comment]
you need to install make and gcc:
```
sudo apt install make gcc
```
other required packages are listed in [this page](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).
