### ISSUE TITLE
i can not see the symbols when opening an example 

### ISSUE THREAD

**Issue by princeTem** [StefanSchippers/xschem#188]
Dear Stefan
i use a standalone ubuntu system , i followed the steps as your video of installation , but when i open the example , i found the following ,, i tried every possible way to find a solution 
can you help me with that 
![image_copy](https://github.com/StefanSchippers/xschem/assets/62261043/bf0afcc0-e034-45a3-8ffa-84f1b6760a15)

**Comment by StefanSchippers** [comment]
what commands did you run  exactly?

go into the source xschem directory and do again these commands:

./configure 
make
sudo make install

**Comment by princeTem** [comment]
dear Stefan 
thank you , it worked after i removed the previous installation ,,, and i installed it from beginning , then i used the entry ./configrue  without the " prefix" 
it seems that at the first installation , i used the prefix with a directory which caused me trouble as i am new on ubuntu 
thanks alot again 
regards
