### ISSUE TITLE
Preserve text orientation during symbol rotation and flipping

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#189]
Hello!
I have a question - is it possible to preserve text orientation regardless of symbol rotation and flipping? Mainly I need it during rotation to save readability of component properties - of course I can make text floating and manually rotate each of it, but it is very tedious for large circuits...

Thank you in advance.

**Comment by StefanSchippers** [comment]
It is better to make symbol texts floaters before rotating the symbol. So you don't have to rotate and align the texts, just move it to the best place.

**Comment by georgtree** [comment]
Good idea 💡
