### ISSUE TITLE
simulation fail, showing a lots of warnings and an error

### ISSUE THREAD

**Issue by pauloohaha** [StefanSchippers/xschem#19]
Hi,
I have followed your detailed video on youtube to install xschem on my ubuntu system in a virtual machine run on windows.
I have finished all the installations. However, when I tried to run the simulation, I met some problems.

The first problem is already solved, but I think maybe it is good to let you know:
When I ran the simulation, it showed this:
![first problem1](https://user-images.githubusercontent.com/85469000/126928161-7fdbd9e2-c769-4f10-83ec-a3946bee2603.jpg)

I consult with one of my friends, who have also met this problem and sent you an email, and solved the problem by modifing the path in nfet_20v0_MODEL and TT MODELS:
<img width="668" alt="first problem2" src="https://user-images.githubusercontent.com/85469000/126928356-ca2aba95-9df1-42ee-8f9c-b6c8fab3194f.png">

Then I met the second problem, which is the main problem that I wish to get help from you:
Afther the paths are modified, I ran the simulation again. But this time it stuck at here for about 1min:
<img width="260" alt="simulation_start" src="https://user-images.githubusercontent.com/85469000/126928501-7edf6cbb-896c-4006-aee6-4bfed08d5efe.png">

Then it shows a lots of warnings and stuck again:
<img width="273" alt="simulation_warnings" src="https://user-images.githubusercontent.com/85469000/126928534-4e5abda2-1290-4801-b878-b6469b69f9fe.png">

After few mins, it shows an error:
<img width="257" alt="simulation_error" src="https://user-images.githubusercontent.com/85469000/126928568-a610ac44-c94e-4e4d-9735-762e2d7115c1.png">

I have looked up in internet, but it seems that there is no existing solutions (if I didn't missed it

Anyway, thanks for your contribution and help!!!

**Comment by StefanSchippers** [comment]
you must replace the `.include /path/to/sky130.lib.spice` with:
`.lib /path/to/sky130.lib.spice tt`

Stefan

**Comment by pauloohaha** [comment]
Let me show the content of my nfet_20v0_MODEL and TT_MODELS:

nfet_20v0_MODEL:
![nfet](https://user-images.githubusercontent.com/85469000/127092586-01ad6434-2847-496d-9c81-ac91e1343701.png)

TT_MODELS:
![TT](https://user-images.githubusercontent.com/85469000/127092612-12b7b7d9-e042-4236-82bd-545b1017a669.png)

 I have also creadted the .spiceinit file.

The situation is now:
If I start simulation, it pop up a lots of messages (a small part of them):
![messages](https://user-images.githubusercontent.com/85469000/127093002-29ff07af-7ecf-4ad2-85e3-8dc741e6d89d.png)
and then:
![ysn](https://user-images.githubusercontent.com/85469000/127092767-f389479a-8029-4c6f-9717-9d7ed99e9496.png)

If I type y and then enter:
![result](https://user-images.githubusercontent.com/85469000/127093116-961907d4-be09-41f7-a823-f5d28ce523c8.png)

It seems that something is still wrong.

**Comment by StefanSchippers** [comment]
If you use directly the `sky130_fd_pr` tree you probably need to apply this [patch](https://github.com/StefanSchippers/xschem_sky130/blob/main/sky130_fd_pr.patch) file.
Download the [file](https://raw.githubusercontent.com/StefanSchippers/xschem_sky130/main/sky130_fd_pr.patch) from github, call it `sky130_fd_pr.patch`, go into the `.../sky130_fd_pr/latest/` directory and execute:

`patch -p2 < sky130_fd_pr.patch`

**Comment by pauloohaha** [comment]
I copied the `sky130_fd_pr.patch` file from the git clone during the installation and put it in the `.../sky130_fd_pr/latest/` directory.

Then I ran `patch -p2 < sky130_fd_pr.patch` and getting this:
<img width="583" alt="patch fail" src="https://user-images.githubusercontent.com/85469000/127113692-1b62270a-ba38-44df-ba9d-8999d226fd69.png">

**Comment by StefanSchippers** [comment]
Only a single file failed patching, this is probably because there is a newer version of the skywater pdk,. No problem, 
Run simulation and see if errors are now gone.

**Comment by pauloohaha** [comment]
Good news, some graphs pop up:
<img width="978" alt="graphs" src="https://user-images.githubusercontent.com/85469000/127114779-da42da30-3657-456f-bc02-ac81ef285ce0.png">

But are them kind of strange? I think there is still something wrong.

The message from the simulation:
<img width="287" alt="result_imprefect2" src="https://user-images.githubusercontent.com/85469000/127114864-40959fe8-f89e-468a-8f93-ccaf1b4b1cea.png">

There are a lot of 'ignored' messages:
<img width="284" alt="result_imprefect3" src="https://user-images.githubusercontent.com/85469000/127114945-7c5165c4-aaf5-4050-8a05-8967fc5e6119.png">

Message at last:
<img width="276" alt="result_imprefect1" src="https://user-images.githubusercontent.com/85469000/127114987-a5b0ee05-a834-4e92-86c7-ea4491f618e7.png">

**Comment by StefanSchippers** [comment]
Your ngspice version is too old, 
clone ngspice from [git](https://git.code.sf.net/p/ngspice/ngspice), go into the ngspice/ directory, switch to pre-master branch (`git checkout pre-master`) and follow the instructions in the INSTALL file.

you need to run `./autogen.sh`
then create a `release/` directory under the `ngspice/` tree, cd to `release/`, and run:
`../configure --with-x --enable-xspice --disable-debug --enable-cider --with-readline=yes`
followed by '`make`' and '`make install`'

**Comment by pauloohaha** [comment]
Everything went well!
<img width="1018" alt="done" src="https://user-images.githubusercontent.com/85469000/127119434-72990084-ba2d-4dff-9e84-eb0ed538f9f7.png">

Huge thank for your generous and timely help!!!!

(b.t.w. I guess from your name that you maybe a German and Vielen Dank!!!!
