### ISSUE TITLE
Preview symbol command issue

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#194]
Hello!
I tried to generate preview of the symbol with preview_window command:
`toplevel .symwin -width 200 -height 200`
`xschem preview_window create .symwin`
`xschem preview_window draw .symwin /usr/local/share/xschem/xschem_library/devices/cccs.sym`
But it doesn't show anything:
![image](https://github.com/StefanSchippers/xschem/assets/113975847/828519a4-57d9-4129-a590-7476ff1b4f4d)
No error in terminal.
Thank you in advance!

**Comment by StefanSchippers** [comment]
try this:
```
toplevel .symwin -width 200 -height 200 -bg {}
xschem preview_window create .symwin
xschem preview_window draw .symwin /usr/local/share/xschem/xschem_library/devices/cccs.sym
bind .symwin <Expose> {xschem preview_window draw .symwin /usr/local/share/xschem/xschem_library/devices/cccs.sym}
```
the toplevel is created without a background, otherwise there is a race condition between xschem drawing the circuit in it and tk painting the background.

The bind command ensures the window will be refreshed if it is obscured / iconified

**Comment by StefanSchippers** [comment]
I have made some updates so that previous commands can be simplied as:
```
toplevel .symwin -width 200 -height 200 -bg {}
xschem preview_window create .symwin
xschem preview_window draw .symwin /usr/local/share/xschem/xschem_library/devices/cccs.sym
bind .symwin <Expose> {xschem preview_window draw .symwin}
```

**Comment by georgtree** [comment]
All works great, thank you!

A side question - how to add to xschemrc file a `source` of script that contains `xschem` command?
It tells me that:
![image](https://github.com/StefanSchippers/xschem/assets/113975847/c398ab68-4808-44ac-9fe5-fe6c24bfabd4)
Looks like I have to load some xschem package before the loading of my script...

**Comment by StefanSchippers** [comment]
you need to use this:
` set postinit_commands {source /path/to/file}`

**Comment by georgtree** [comment]
Hello!
I tried add this command to run after init, but it doesn't work:
`set postinit_commands {source /home/george/MDPSBLib/gui_plugin/component_palette_grid.tcl}`
I added puts command there but it doesn't show at startap, and at the same time the default command 
`set postinit_commands {puts [xschem get version]}` works as it should.
Maybe I should add something to my script?

**Comment by georgtree** [comment]
I add this:
`frame $paletteFrame.symbPreview -bg {}
bind $paletteFrame.symbPreview <Expose> {xschem preview_window draw $paletteFrame.symbPreview}
xschem preview_window create $paletteFrame.symbPreview`

And got segfault at script run, without this line:
`bind $paletteFrame.symbPreview <Expose> {xschem preview_window draw $paletteFrame.symbPreview}`
window works but I have distorted view when drag top window which contains preview window:
![image](https://github.com/StefanSchippers/xschem/assets/113975847/16bba464-6125-433a-a9b7-2f98c422ab31)

**Comment by georgtree** [comment]
Now my GUI looks like this:
![image](https://github.com/StefanSchippers/xschem/assets/113975847/cfe2e461-601b-4685-ae58-01d9766830fd)
still have segfault when I try to bind...

**Comment by georgtree** [comment]
I added 
`ttk::style configure TLabelframe -transparentcolor`
but it doesn't help :(

**Comment by georgtree** [comment]
I found the issue, I am an idiot, sorry
