### ISSUE TITLE
Preview .tcl symbol with preview_window

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#195]
Hello!
Question - is it possible to preview generator symbol with command `preview_window` with default input for generator?
It should be possible somehow, but I need your advice, thank you.

**Comment by StefanSchippers** [comment]
it is possible, to render a generator you must call its name with parenthesis, perhaps with arguments. Since in a preview window you are not usually giving any parameters the generator script should be usually architected to accept no arguments and do a "default" action. 

To preview a generator tier.tcl:
xschem preview_window draw .p {xschem-repo/trunk/xschem_library/generators/tier.tcl()}

![1](https://github.com/StefanSchippers/xschem/assets/69359491/c4c43691-ae69-49d0-99b4-4f164ae405c6)

**Comment by georgtree** [comment]
Great, thank you, I have many components that use scripts not for changing the symbol but it's properties in device_model attribute. I will try it today's evening.

**Comment by georgtree** [comment]
Hello, don't understand why, but the else statement doesn't work, if tag is 'element', the preview window works as expected, if not, nothing happens, even `puts` doesn't output anything to console. Maybe you know why is it so? 
`    set focusTag [$pf.palettePanwin.comp.tree item [$pf.palettePanwin.comp.tree focus] -tag]
    if {$focusTag eq {element}} {
        puts 1
        $pf.palettePanwin.prev configure -background {}
        xschem preview_window draw $pf.palettePanwin.prev [$pf.palettePanwin.comp.tree focus]
        bind $pf.palettePanwin.prev <Expose> {xschem preview_window draw $pf.palettePanwin.prev }
        bind $pf.palettePanwin.prev <Configure> {xschem preview_window draw $pf.palettePanwin.prev }
    } else {
        puts 2
        $pf.palettePanwin.prev configure -background {}
        xschem preview_window draw $pf.palettePanwin.prev "[$pf.palettePanwin.comp.tree focus]()"
        bind $pf.palettePanwin.prev <Expose> {xschem preview_window draw $pf.palettePanwin.prev }
        bind $pf.palettePanwin.prev <Configure> {xschem preview_window draw $pf.palettePanwin.prev }
    }`

**Comment by georgtree** [comment]
All works, thank you!
Additional question - is it possible to show hidden by default text in preview window?
Thank you in advance!

**Comment by StefanSchippers** [comment]
I think you can temporarily enable the global variable **show_hidden_texts**:

```
set save $show_hidden_texts
set show_hidden_texts 1
xschem preview_window draw .path /path/to/symbol.sym
set show_hidden_texts $save
```

**Comment by georgtree** [comment]
Ah, right, thank you!
