### ISSUE TITLE
Check simulation status via TCP/IP socket

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#200]
Hello!
I have a question: how to check if simulation finished via TCP/IP socket from TCL script?
I was able to connect to xschem in non-gui, detached from terminal regime, send commands to open file, netlist, simulate, etc.
As I understand, I have to check some status variable to understand that simulation is finished and I can load .raw file.
Maybe it is more wise to use xschem only for netlist generation and reading raw files, while simulation is run with ngspice directly...
Could you please point in right direction?
Thank you in advance, George.

**Comment by georgtree** [comment]
Update - there is an optional callback, but it doesn't run when simulation finished - just at the moment it is started. I think it depends on how the simulation command is built...

**Comment by georgtree** [comment]
Ok, I found the way, the simulation should be set background `set sim(spice,2,fg) 0`, and the call back works just fine :)

**Comment by georgtree** [comment]
Maybe there is a more elegant way than using socket on local machine?
I think about sending commands directly to xschem tcl console, but not sure how do this :(

**Comment by StefanSchippers** [comment]
Here a simple way (in the xschem tcl console) to check if simulation is runing or if it has finished.
Any time you call simulate an id variable is returned. This id can be used to query simulation status.
xschem sets various variables when running a simulation, one of these is array variable execute(cmd,$id) , it returns the ngspice command line being executed. When simulation is finished the array variable is deleted.
you can use info exists execute(cmd,$id) t check if simulation is running.
The use of the `id` variable allows you to run multiple simulations in parallel.
```
schippes@asus:~$ xschem poweramp.sch
xschem [~] xschem netlist
0
xschem [~] set id [simulate]
Simulation started: execution ID: 0
0
xschem [~] puts $execute(cmd,$id)
xterm -e {ngspice -i "/home/schippes/.xschem/simulations/poweramp.spice" -a || sh}
...
...
xschem [~] puts $execute(cmd,$id)
can't read "execute(cmd,0)": no such element in array
while evaluating puts $execute(cmd,$id)
xschem [~] info exists execute(cmd,$id)
0
```

The following example script runs 3 siulations in parallel on a schematic `poweramp.sch` and waits untill all 3 sims are completed.
```
xschem load poweramp.sch
set id_list {}

xschem netlist
set id [simulate]
delay 1000
lappend id_list $id

# change VPP, output file name and input signal amplitude
set commands [xschem getprop instance NGSPICE value]
regsub {\.param VPP=50} $commands {.param VPP=30} commands
regsub -all {poweramp\.raw} $commands {poweramp1.raw} commands
xschem setprop instance NGSPICE value $commands
xschem setprop instance V3 value {dc 0 sin 0 0.5 {frequ} 1m}

xschem netlist
set id [simulate]
delay 1000
lappend id_list $id

# change again VPP and output file name
regsub {\.param VPP=30} $commands {.param VPP=25} commands
regsub -all {poweramp1\.raw} $commands {poweramp2.raw} commands
xschem setprop instance NGSPICE value $commands

xschem netlist
set id [simulate]
delay 1000
lappend id_list $id


# poll loop
while {1} {
  delay 1000
  set busy 0
  foreach id $id_list {
    set var "execute(cmd,$id)"
    if {[info exists $var]} { set busy 1}
  }
  if {!$busy} { break }
}
puts Done
```

**Comment by georgtree** [comment]
Wow, thank you, it is much more than I expected, thank you, I will use this example for control of xschem from tcl script!

**Comment by StefanSchippers** [comment]
If there is something you can't get working let me know. All these things need some 3rd party testing :-)

**Comment by georgtree** [comment]
I tried both things, all works, thank you!

**Comment by georgtree** [comment]
Hello!
I tried it now and command simulate return not the id but string ` Simulation started: execution ID: 0`.
is it possible to return back to returning just an id?
