### ISSUE TITLE
Manual discrepency "propag" and "propagate_to"

### ISSUE THREAD

**Issue by hammal** [StefanSchippers/xschem#203]
There seems to be a discrepancy between the property "propag" and "propagate_to" on the manual page.
Specifically, when comparing with my Xschem version 3.4.5, the image [doc/xschem_man/edit_property.png](https://github.com/StefanSchippers/xschem/blob/master/doc/xschem_man/edit_property.png)
) in the [doc/xschem_man/xschem_properties.html](https://github.com/StefanSchippers/xschem/blame/76fe0d3ef360465505e88b0d70108cc39aab0e88/doc/xschem_man/xschem_properties.html#L44C2-L44C31) is not up to date and does not agree with the `propag=1` reference in the following paragraph.

**Comment by StefanSchippers** [comment]
Thank you, now fixed.
