### ISSUE TITLE
TAB symbol displaying issue

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#205]
Hello!
I found the issue with TAB symbol in text block:
![image](https://github.com/StefanSchippers/xschem/assets/113975847/564c2fe9-3e49-458a-97df-9d1e6781f2eb)
It renders it like a square, for now I use four spaces for indentation, but maybe there is a quick fix for it?
Thank you in advance!

P.S. the source of text is:
[example.txt](https://github.com/StefanSchippers/xschem/files/15387932/example.txt)

**Comment by StefanSchippers** [comment]
Yes, TAB is not handled (yet) so you get a weird 'unprintable char' placeholder.
TAB is not a character to display, but an information to use to set the position of the next character.
I will eventually handle that.

**Comment by StefanSchippers** [comment]
George, 
can you please update xschem and test TABs in your examples? 
It should work now.
tcl variable `tabstop` sets the tab position (default 8) 
you can set this in xschemrc:
`set tabstop 4`
to change the default tab stops.

**Comment by georgtree** [comment]
Hello, all works, thank you!
