### ISSUE TITLE
RFC: Different color for currents and voltages in back-annotation

### ISSUE THREAD

**Issue by qpwo** [StefanSchippers/xschem#207]
I think the annotations would be easier to read if the currents were in a different color. It can get crowded.

![image](https://github.com/StefanSchippers/xschem/assets/10591373/05295796-5752-4c0f-a434-173dde6ff156)

**Comment by StefanSchippers** [comment]
This can now be done in two ways:
1) change the symbol and move the current / voltage text on a different layer 
2) on a specific symbol instance add attribute text_layer_n = lay, where n is the text number in the symbol (first=0, second =1, and so on, you can see the text position in the symbol by clicking on it and pressing Shift-S)
example: text_size_4=9  --> move the symbol fourth text item to layer 9

The second solution does not require to change the symbols library, but needs the above attribute on all instances where text must be rendered on a different layer.

**Comment by StefanSchippers** [comment]
I have modified the devices/ xschem base symbols to display current annotations (@spice_get_current) on layer 12 (blue)
![1](https://github.com/StefanSchippers/xschem/assets/69359491/ee6c9986-8613-4ebd-b242-1d74ec963573)

**Comment by qpwo** [comment]
Awesome! Would've taken synopsys a decade 


![image](https://github.com/StefanSchippers/xschem/assets/10591373/1a2ad994-c54a-4739-9eef-0539dc30ce2e)
