### ISSUE TITLE
[UI/UX Improvement] Allow to terminate simulation early.

### ISSUE THREAD

**Issue by armleo** [StefanSchippers/xschem#21]
Right now, there is no way to stop running simulation. It would be great if early termination of the simulation were possible.

**Comment by StefanSchippers** [comment]
The best option is to run the simulation in interactive mode. If you are referring to ngspice, using interactive simulation will open a terminal window, inside the terminal ngspice is doing the simulation. Pressing 'ctrl-c will stop the simulation, by using the 'resume' command simulation should restart. (This often does not work for me, after stopping simulation it does not resume).
