### ISSUE TITLE
./configure: not found

### ISSUE THREAD

**Issue by Camisad0** [StefanSchippers/xschem#212]
Hi,

I'm encountering error during the ./configure part when installing xschem.

Kindly refer to the attached image.
![Configure Not Found](https://github.com/StefanSchippers/xschem/assets/117753129/4de5d459-e464-4fb7-938a-5dcea368daee)

Looking forward to your inputs.

Thanks!

**Comment by Camisad0** [comment]
Libraries checked 
![Libraries](https://github.com/StefanSchippers/xschem/assets/117753129/9ac5feaf-e1a3-4401-863d-6315823cc0f9)

**Comment by StefanSchippers** [comment]
install all the packages listed [here](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html) and run ./configure again.

**Comment by StefanSchippers** [comment]
If configure is still failing and your system has no /usr/bin/cc link try this:
./configure --CC=/usr/bin/gcc

**Comment by StefanSchippers** [comment]
No follow up, closing.
