### ISSUE TITLE
Issue with tabulate 

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#214]
Hello!
Is it possible to remove gaps between vertical lines?

![image](https://github.com/StefanSchippers/xschem/assets/113975847/edbd71f1-57a8-4967-9096-d0612c40cc3d)

**Comment by StefanSchippers** [comment]
The presence of gaps or not depends on the font. You can trim the line spacing by experimenting with this xschemrc setting:
```
#### Scale line spacing by this number
# set cairo_font_line_spacing 1.0
```
Do not go far from 1.0, so you may try 0.97 or similar values.

**Comment by georgtree** [comment]
Yeah, you are right, thank you
