### ISSUE TITLE
Manual loading of raw files

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#215]
Hello!
Is it possible to switch off autoloading of raw files when they are specified in the graphs explicitly?
Now if I load one raw file manually, the rest of them are loaded too.
I want to fully control which files are loaded and in what sequence, to work with them later.
Thank you in advance!

**Comment by StefanSchippers** [comment]
I will improve that, this will take some time. Previously xschem allowed only one raw file to be loaded. Now multiple files can be loaded, but the load/unload mechanism is still primitive.

**Comment by StefanSchippers** [comment]
Graphs now have an auto load checkbutton that loads waves automatically or not. Please test.
![1](https://github.com/StefanSchippers/xschem/assets/69359491/92210b54-afcc-402f-9ef8-5c6060127e74)

**Comment by georgtree** [comment]
Hello, just tested, all works, thank you very much, this option allows more flexible annotation
of schematics :)

**Comment by georgtree** [comment]
Hello!
Is it possible to manually load multiple raw files without auto load tick set?
Now I can load multiple files only with this tick, if I load multiplefiles with xschem raw read, it remove previous raw file from the memory.
Thank you.
