### ISSUE TITLE
'ngspice: no such file or directory

### ISSUE THREAD

**Issue by abdelrahmanali15** [StefanSchippers/xschem#222]
## Error when Pressing Simulation button 
![image](https://github.com/StefanSchippers/xschem/assets/131778595/67a35051-80c6-4868-96b9-34b0577ac322)

but in the same terminal I can run the simulation manually with the same command 

![image](https://github.com/StefanSchippers/xschem/assets/131778595/b4800fb2-c068-40bd-aade-719a57786573)

I don't know why does this happen. If you have an insight.

**Comment by StefanSchippers** [comment]
In xschem go to Simulation ->Configure simulators and tools and replace the word ngspice with the full path of the executable as it is installed on your system.
![1](https://github.com/StefanSchippers/xschem/assets/69359491/11309ba2-1b3a-48a6-90bd-3a335c4f2944)

**Comment by abdelrahmanali15** [comment]
Working Now thank you for your help
