### ISSUE TITLE
Xschem with Sky models won't launch

### ISSUE THREAD

**Issue by Rafahkz** [StefanSchippers/xschem#224]
Hello!

I'm having some trouble when trying to launch xschem with SkyWater models. In my other computer, when I type "xschem &" it runs, but in the PC I'm using, nothing happens... Maybe it is a simple question, but I don't know what to do. Thanks!

![Img](https://github.com/StefanSchippers/xschem/assets/174132434/b2144efd-c7db-41b2-a3af-65462fca7849)

**Comment by StefanSchippers** [comment]
- Do you have other graphical applications working on this machine (xclock)?
- What happens if you do `xschem` without the '&'?
- What is printed if you do `xschem -v` ?

**Comment by Rafahkz** [comment]
Hi, Stefan. Thanks for the repply.

1) I'm currently not using other graphical applications in this machine;

2)  If use only "xschem", the same thing happens, but the application won't launch;
![image](https://github.com/StefanSchippers/xschem/assets/174132434/3cf926b1-1507-48ec-9214-9591e17c914e)

3) With this command, the CLI displays
![image](https://github.com/StefanSchippers/xschem/assets/174132434/fc740dd8-6ac9-462b-be6b-730748a4e4b1)

**Comment by StefanSchippers** [comment]
Ok you have a very old xschem package instaled with apt.
Remove the installed xschem:

- sudo apt purge xschem

Then follow this tutorial to install xschem: https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html

**Comment by Rafahkz** [comment]
Hey, Stefan!

In my other computer, it works fine! Even with the older version
![image](https://github.com/StefanSchippers/xschem/assets/174132434/21e56408-dfe7-41e0-a368-b77f45cb8012)

Now I'm on vacation, but as soon as I come back to that first computer, I will try the tutorial you mentioned. Thanks for your answers!
