### ISSUE TITLE
MOS Region of Operation

### ISSUE THREAD

**Issue by Camisad0** [StefanSchippers/xschem#226]
Hi Stefan, I'm just wondering if there's a way to know or generate a spice report to see what the region of operations of your transistors in your respective design? Thanks!

**Comment by StefanSchippers** [comment]
I have done something similar in xschem, basically evaluate device currents / voltages and highlight devices which meet a certain criteria. It's not trivial, you have to write a script for this. 

I don't know if ngspice has some native instructions to print the device status

https://github.com/user-attachments/assets/7763fec0-df4f-4917-bd72-24265bcd2de7

**Comment by StefanSchippers** [comment]
Referring to above video, use Control-Click to execute the launcher script. Here the script for reference:
```
tclcommand="
xschem unhilight_all
set incr_hilight 0
foreach {i n t} [xschem instance_list] {
  if { $t eq {nmos} || $t eq {pmos}} {
     # ... The traditional TCL quoting hell....
     #               tclcommand         set inst
     #    \\\\\\\[       -->      \\\[   -->     \[
     set inst *${path}x[string tolower $i]*\\\\\\\[id\\\\\\\]*
     lassign [array get ngspice::ngspice_data $inst] node value
     # puts $inst
     if { $value > 1e-6 } {
       xschem set hilight_color 0
       xschem hilight_instname $i fast
     }
  }
}
xschem redraw

"
```

**Comment by Camisad0** [comment]
I see, thanks for sharing this.

Just a follow up question, how do I know what are the process parameters of the Sky130 MOS transistors (i.e. gm, ro, Kn, etc.)? I need some of this information for me to compute the required specifications of my design.

**Comment by StefanSchippers** [comment]
Look at chapter 27 of latest ngspice user manual. In particular paragraph 27.0.6.23 for BSIM4 device parameters

**Comment by Camisad0** [comment]
Is there a specific way to print all of the intrinsic properties of your MOS say gm, ro, Kn etc.? Can you share a sample script?
Thanks a lot.

**Comment by StefanSchippers** [comment]
You need to explicitly save the mos parameters, like in:
```
.control
save all

save @m.x1.xm5.msky130_fd_pr__nfet_01v8[gm]
save @m.x1.xm5.msky130_fd_pr__nfet_01v8[gds]
save @m.x1.xm5.msky130_fd_pr__nfet_01v8[vth]
...
op
write circuit.raw
.endc
```
You run a OP analysis and write the raw file.
xschem is able to load the operating ppoint (Waves -> OP annotate)
and you can place `ngspice_get_value.sym` symbols to display the parameters:
![1](https://github.com/user-attachments/assets/b8ff08a3-3e87-4be1-8a5a-57fab3bf3b4e)

**Comment by Camisad0** [comment]
Hi Steffan, am I doing this correctly? I'm not seeing any values like gm, vth. Also tried using the ngspice_get_value.sym and no values are showing. Appreciate the help. Thanks!
![A](https://github.com/user-attachments/assets/63a4f4fa-1ad5-48c3-aaac-1fc877cc6b2f)
![B](https://github.com/user-attachments/assets/87c6a278-fb8a-48e1-92ea-7be1c41c9280)
![C](https://github.com/user-attachments/assets/7a27006f-0b65-445c-8e22-3a58d447f68b)

**Comment by StefanSchippers** [comment]
you need to write in ngspice .control block:
```
save @m.xm1.msky130_fd_pr__nfet_01v8[gm]
save @m.xm2.msky130_fd_pr__pfet_01v8[gm]
```
also add:
`.options savecurrents `
before the .control block.
This will save all [id] currents for all transistors.

**Comment by Camisad0** [comment]
Hi Steffan,

Thanks. I can see gm and id now. However for other parameters like Vgs and Vt0 I cannot see them in the op annotate command. It does not show in the ngspice_get_value.sym as well. Kindly advise.

![missing](https://github.com/user-attachments/assets/bac697df-9230-4b73-bf50-0a16343b74f2)

**Comment by StefanSchippers** [comment]
Mos devices show Id, gm and (in smaller font) vgs and vds. For other parameter place a `ngspice_get_value.sym` and specify the node and the description, see image.
**Note** that vgs and vth are voltages so the node must be specified inside a v(...), like `node=v(@m.xm5.msky130...[vth])` The v(...) is not needed in the save instruction.

![1](https://github.com/user-attachments/assets/5cf0dd68-aa7a-4a53-bcb9-5d88fcfae5db)

**Comment by Camisad0** [comment]
Thanks Steffan.

However, I'm still not seeing the vgs parameter in the schematic even if I zoomed into the MOS. It only shows when I use the ngspice_get_value.sym. Can you clarify more on this and if I might have missed something on my script?

![kp](https://github.com/user-attachments/assets/36bea684-d0e2-4ddc-8380-af12f793dfc3)

Also, if you can see in the image, I tried using the similar script to view Kp, but I am not seeing it appear in Op Annotate. 

Please advise.

Thanks a lot Stefan.

**Comment by StefanSchippers** [comment]
the vgs and vds showing was added on may 3. If your pdk installation is older than that you will not see. 
You can go to the open_pdks git repository, do a git pull, followed by a make update and make, make install to update the symbols. 

Or you can pick the MOS symbols [here](https://github.com/StefanSchippers/xschem_sky130/tree/main/sky130_fd_pr) and replace the old ones.

**Comment by Camisad0** [comment]
I see, thanks for the information.

How about the Kp not showing? I've tried using the example script but failed to show the parameter. 

Also, do you happen to know if Sky130 has a documentation on the intrinsic properties of its MOS models or do I have to always explicitly code them in NGSPICE to display them?

Thanks.

**Comment by StefanSchippers** [comment]
I don't know about the Kp parameter, however the internal parameters available for MOS devices are documented in chapter 27 or the [ngspice user manual ](https://sourceforge.net/projects/ngspice/files/ng-spice-rework/43/ngspice-43-manual.pdf/download) (see BSIM4).

Details for sky130 devics are present [here](https://skywater-pdk.readthedocs.io/en/main/rules/device-details.html). It is not complete, but this is what i have seen so far.

**Comment by Camisad0** [comment]
Kp is the process transconductance parameter as stated in CH27 in NGSPICE manual. However, Im having a hard time accessing its value in NGSPICE or maybe it is not yet a feature? I need those intrinsic values for my design calculations. 

![image](https://github.com/user-attachments/assets/c29b35c1-fe06-49c7-be98-0c26dbf5355b)

I've also noticed that the Vt of my MOS tends to vary which is counterintuitive to what I assume should be standard to all MOS model under fd_pr_01v8 model.

**Comment by StefanSchippers** [comment]
Sky130 models are BSIM4, not MOS1

**Comment by Camisad0** [comment]
For the Vt parameter, am I right to assume the Vt should be standard to all basic 01v8 SKY130 NMOS/PMOS since its an intrinsic parameter? Because I notice that it changes with W/L or Vgs.

**Comment by StefanSchippers** [comment]
How these parameters are defined and calculated is a complex task. Even the ngspice developers have trouble figuring that out, since they incorporated the berkeley BSIM models and don't know every detail of the equations.
