### ISSUE TITLE
Custom cursors

### ISSUE THREAD

**Issue by trongcuhp** [StefanSchippers/xschem#227]
How do I create a mouse cursor that, when pressed, prints its properties in the terminal?

**Comment by StefanSchippers** [comment]
Do you mean a graph cursor that prints X axis value and waveform values at cursor position in the terminal?

**Comment by trongcuhp** [comment]
yeah

**Comment by StefanSchippers** [comment]
For details about the xschem commands (getprop, selected_set, raw) see the doc [here](https://xschem.sourceforge.io/stefan/xschem_man/developer_info.html#cmdref).
