### ISSUE TITLE
.spice export changes MOSFETs from 4 to 3 port devices if LVS-netlist is enabled

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#231]
is this intended or an error? did i miss some export option?

if i export without `Simulation::LVS::LVS netlist " ...` the line for X3 is:
`X3 net5 ip net1 VDD sg13_hv_pmos w={12*pw} l={2*pl} ng=5 m=2`
if i enable it, i get.
`X3 net5 ip net1 sg13_hv_pmos w={12*pw} l={2*pl} m=2 ng=5`
here is the VDD bulk-contact missing.

**Comment by olisnr** [comment]
it seems, that this behavior (missing bulk connection) is only seen, if the top-schematic hasnt any OUTPUT-port. i think this is an error, what do You think?

**Comment by olisnr** [comment]
`Simulation::LVS::Top level is a .subckt` writes a netlist with 4 pin MOSFETs

**Comment by StefanSchippers** [comment]
Can you attach the schematic that has this problem?

**Comment by olisnr** [comment]
[lvs.zip](https://github.com/user-attachments/files/16949699/lvs.zip)

the `OTA_TOP_LVS.spice` is generated with the LVS-option enabled. i used the newest version from github

**Comment by StefanSchippers** [comment]
Looking at the netlist rule of the mos symbols I see this:
```
lvs_format="@name @pinlist @model w=@w l=@l m=@m ng=@ng"
format="@spiceprefix@name @pinlist @substrate @model w=@w l=@l ng=@ng m=@m"
```
The symbols have 3 physical pins (Drain, gate, source) and the 4th connection (substrate) is specified with attribute (substrate=...) 

The netlist rule for simulation (spice) netlist (without LVS-option enabled) has a **@substrate** attribute after **@pinlist**, while the LVS netlist rule (`lvs_format` attribute) has no **@substrate** specified.

You need to add **@substrate** after **@pinlist** in `lvs_format` attribute if you want all 4 connections in all netlist variants.

**Comment by StefanSchippers** [comment]
In the mos symbols it is better to move the m=@m (multiplicity) as last parameter in lvs_format (some simulators require the m=.. to be the last instance parameter):
`lvs_format="@name @pinlist @substrate @model w=@w l=@l ng=@ng m=@m"`

**Comment by olisnr** [comment]
super thanks!
