### ISSUE TITLE
How can I fix that?

### ISSUE THREAD

**Issue by trongcuhp** [StefanSchippers/xschem#232]
![image](https://github.com/user-attachments/assets/5a1d29bf-70e6-4269-a85a-e2eca4d75abb)

**Comment by StefanSchippers** [comment]
If you plan to use Xschem on windows go to this URL and read carefully the README_WIN and INSTALL_WIN files.

**Comment by trongcuhp** [comment]
thank for your help

**Comment by trongcuhp** [comment]
![image](https://github.com/user-attachments/assets/982df22e-6c1d-46da-9b57-78e2357bb975)
I have installed fully but still get this error, do you have any way to run on win like INSTALL_WIN

**Comment by trongcuhp** [comment]
> If you plan to use Xschem on windows go to [this URL](http://cgi.repo.hu/cgi-bin/minisvn.cgi?cmd=browse&repo=xschem&path=trunk/XSchemWin) and read carefully the README_WIN and INSTALL_WIN files.

help me!

**Comment by StefanSchippers** [comment]
I don't have windows, so my help is limited. 
Read carefully the README_WIN file and build the program with VisualStudio 2022.

**Comment by StefanSchippers** [comment]
You can get a pre built windows package by downloading [XSchem-3.4.5-64bit.msi](http://repo.hu/projects/xschem/releases-bin/XSchem-3.4.5-64bit.msi) and installing it on your machine.

**Comment by trongcuhp** [comment]
> You can get a pre built windows package by downloading [XSchem-3.4.5-64bit.msi](http://repo.hu/projects/xschem/releases-bin/XSchem-3.4.5-64bit.msi) and installing it on your machine.

can u give me links, I cant download file that u just gave me

**Comment by trongcuhp** [comment]
or can you make videos instruct to build on window with micro visual studio,

**Comment by StefanSchippers** [comment]
If you can not download this installer file it is probably a windows protection issue.
