### ISSUE TITLE
How can I custom icons and logo?

### ISSUE THREAD

**Issue by trongcuhp** [StefanSchippers/xschem#236]
Can you give me some suggestions to custom icons?

**Comment by StefanSchippers** [comment]
The xschem icon is a small XPM image with a transparent background, it is in file icon.c. You can open this file with an image viewer or view it with an editor, it is an ASCII file. 
xschem creates a X11 pixmap from this icon file and sends the icon hint to the window manager, so it will be used for the program.

The checkerboard pattern in image below indicates that the image has transparent background.
![1](https://github.com/user-attachments/assets/dee3076b-db12-4c23-87b0-189fb52f4d7d)

**Comment by trongcuhp** [comment]
I found it, thank you
