### ISSUE TITLE
XSCHEM Configuration Error : TCL not founf

### ISSUE THREAD

**Issue by Ikram-rs22** [StefanSchippers/xschem#237]
I'm completely new to Xschem and linux. I've install ubuntu in a virtual box. I've installed all the necessary libraries mentioned in the xschem manual but whenever I try to configure xschem, it says the following. But I have tcl8.6.15 installed. Please help me, I'm a new user
![Screenshot 2024-10-03 233708](https://github.com/user-attachments/assets/98ad006f-1119-4e94-b8ff-ffe28983d2a1)

**Comment by StefanSchippers** [comment]
You need to install the tcl libraries:
tcl8.6-dev
and
tk8.6-dev

See the complete list of required packages [here](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).

**Comment by Ikram-rs22** [comment]
Sorry for the late response. Thanks a lot sir. For your co-operation
