### ISSUE TITLE
change in mouse-wheel behavior after tclcommand "xschem annotate_op "

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#240]
in the newer versions of Xschem i found, that sometimes the mouse-wheel changes its function. as example, after running a `tclcommand` with 
`xschem annotate_op ${netlist_dir}/${schematic}_mos${mos_corner}.raw
`
while before the wheel changed the diagram, after it changes the main-window

https://github.com/user-attachments/assets/8c37124f-621d-4395-99b0-ae682c9024e4

**Comment by olisnr** [comment]
and then the zoom is also a bit strange. the clipping could be improved. now it remembers at the cathode-ray oscilloscopes without pre-trigger :)

https://github.com/user-attachments/assets/cb756894-1a39-457a-9154-a809edb39789

**Comment by olisnr** [comment]
this is still the same... i think it has something to do with cinnamon.

**Comment by StefanSchippers** [comment]
I also had **a one time** problem like yours. When entering the graph the mouse pointer did not change to '+' and did not zoom the graph but the window instead. 

But I need to trigger this issue again. and this seems very difficult.

**Comment by StefanSchippers** [comment]
One case when such event occurs is if you press 'm' or 'c' outside the graph with nothing selected to move or copy something (but nothing is selected so nothing happens). the UI enters move or copy mode and you can't zoom the graphs. Pressing Esc (which terminates all pending commands) fixes the issue. 

This is clearly a bug. If nothing is selected 'm' or 'c' must do nothing.

**Comment by olisnr** [comment]
i dont really like that the zooming is switched from window to graph by having the mouse-pointer inside the graph. is it possible to change it to use a `modifier-key` to zoom the or `f` the selected graph? normally, i have the schematics zoomed in, to have a big view of the graph. im with the pointer with high change over a graph. then i want to zoom out, and use the middle wheel, or the `f-key` and instantly regret not first placed the pointer outside of a graph...

**Comment by StefanSchippers** [comment]
This is a good point. I also was planning to do it. Having the graphs moving while working on the schematics is annoying.

I can add an option to do that. I will not change the default as some users may complain.

**Comment by olisnr** [comment]
what do You think about the cliping? its more noticeable in Xyce because the time-steps are adaptive:
![Screenshot 2024-11-29 22:07:14](https://github.com/user-attachments/assets/2521b1a4-51e2-4df7-866b-49601c8999a2)
it this difficult to improve?

**Comment by StefanSchippers** [comment]
> what do You think about the cliping? its more noticeable in Xyce because the time-steps are adaptive: 

In general xschem does not interpolate or extrapolate points to make the waveforms exactly fit the graph area. 
in the image above the first waveform point is the first one found in the raw file that is inside the x axis range. Similarly the last waveform point is the last one in the raw file that is inside the axis range. 

This shows that on that zoom level the simulation density of points is too low. You should reduce the simulator timestep (by increasing the time precision).

**Comment by StefanSchippers** [comment]
> i dont really like that the zooming is switched from window to graph by having the mouse-pointer inside the graph. is it possible to change it to use a `modifier-key` to zoom the or `f` the selected graph? normally, i have the schematics zoomed in, to have a big view of the graph. im with the pointer with high change over a graph. then i want to zoom out, and use the middle wheel, or the `f-key` and instantly regret not first placed the pointer outside of a graph...

the following variable is added in xschemrc:
```
###########################################################################
#### USE CTRL MODIFIER TO OPERATE ON GRAPHS WITH MOUSE & KEYBOARD
###########################################################################
#### if enabled forces to hold Control key pressed to operate on graphs
#### to prevent "graph event stealing to schematic"
#### Default: 0 (not set)
# set graph_use_ctrl_key 1
```

if that graph_use_ctrl_key variable is set to 1 you must hold the COntrol key down to do anything on graphs, otherwise the key/mouse events are directed to the schematic.

If unset everything works as used to.

**Comment by olisnr** [comment]
Yeseses!! much better! Thanks!!!

about the plots, i think You should not think about interpolation or so. You could simply plot all points inside a window PLUS one point before and one after... i think the graphical APi should handle the clipping. or is this wrong?

the thing is: its not interesting to make more datapoints then nesesary: it costs time and electrical work. the nice thing at good time domain simulations is, that they adapt the sample-rate. i can also show You plots over temperature. i have only the points -55 -50 0 20 40 125. zomming looks bad. thats not necessary. or the other example is: .dc simulations over 5 corners, only the MOSFETs, not mention the resistors or the BTj that multiply the possibility even more.

its interesting to simulate whit the minimum of points, there is no real reason not to plot a line to a point outside the graph window.

![Screenshot from 2024-11-29 23-42-15](https://github.com/user-attachments/assets/ecc0d3ab-837d-42f8-95bf-b8ec3d436dc8)

what do You think?

**Comment by olisnr** [comment]
![dc](https://github.com/user-attachments/assets/4842b719-52d1-4092-b475-c98fbb4df5c8)

this is a sweep over a voltage source, that supplies a shunt-regulator over 100Ω:
```
                \".step temp list -55 -50 0 20 40 125\\n\"\\
                \".dc vdd -.5 6 0.2 \\n\" \\
                \".print dc format=raw v(*) i(*)\"\\
```

**Comment by StefanSchippers** [comment]
I have committed a fix to show full x-range of waves without clipping to existing simuation points. This done by plotting one extra point (if existing)  before and after the graph range.

This needs some testing. Can you please see if it works?

**Comment by olisnr** [comment]
Yes perfekt!!! exactly like expected!

now i have to Xschems open. two different schematics & simulations. one is working with zooming the graphs via the new nice cntr-modifier, and opens the graph-dialog via double-Lclick. the other dont zooms the graph even with the cntr-modifier, but only the schematics, and the double-Lclick opens a Text-window:
![Screenshot from 2024-11-30 01-36-46](https://github.com/user-attachments/assets/515b5e47-7b89-4e64-bc2b-13a54909d17d)

i have not started Xschem over a terminal. is there some other thing i could try to find out, why this two Xschems behave so different?

**Comment by StefanSchippers** [comment]
This is strange. I have started more xschem instances and can't see the issue.
Ctrl-Double Lclick the graph brings the above window (that is the graph attributes, without the dialog box presenting them in graphical format) if the graph is selected or if you click very close to the graph borders.

Are you using 2 separate xschem instances? or are you opening a second window/tab with the same xschem process?

**Comment by StefanSchippers** [comment]
I have pushed another fix, in some cases if waveforms are not loaded the graph dialog box does not show up. Update xschem and test your fail example one more time. 
Thank you

**Comment by olisnr** [comment]
i always open Xschem from a file-browser like nemo or nautilus via double-click. i think the problem is connected to the strange zoom-behavior You also saw 1-time. but what speaks against is, pressing `m` or `c` without selection, didnt change anything in this case.

**Comment by olisnr** [comment]
https://github.com/user-attachments/assets/76388e32-0275-4225-ad1b-a5db90631ecb

**Comment by olisnr** [comment]
that was the old Xschem version. i only wanted to show You the effect before closing and reinstalling Xschem...

**Comment by StefanSchippers** [comment]
The behaviour in above video is correct, since the graph you are double clicking is selected (the border is solid grey line, not dashed) If you click outside the graphs on an empty area you unselect everything and the graph dialog box should appear when double clicking the graph (with control if enabled)

**Comment by olisnr** [comment]
[amps_plot_problem.xyce.zip](https://github.com/user-attachments/files/17965153/amps_plot_problem.xyce.zip)
open `amps_plot_problem.xyce/hsens10_3.5mA_15dB_test_xyce.sch` and try double-Lclick a loaded plot.

**Comment by olisnr** [comment]
ah ok, i missed this. now i have to ctnr also for the dialog :)

**Comment by StefanSchippers** [comment]
Canyou send also the xschemrc you are using? you have a lot of options enabled so i test the same condition.

**Comment by olisnr** [comment]
sure [xschemrc.zip](https://github.com/user-attachments/files/17965201/xschemrc.zip) but may be Your last changes did also fix the original zoom-problems i had anyway... 

i will try a bit and tell You if i see another graph-zoom problem if it dares to show up :)

**Comment by StefanSchippers** [comment]
ok, thank you.

**Comment by olisnr** [comment]
i love the new way of graph zooming

**Comment by olisnr** [comment]
1 thing that seems not to work is the cntr-f over a graph to auto-zoom the hole graph. may be there is a line code missing? or is this intended?

**Comment by StefanSchippers** [comment]
On my system it works. may be another key combination Cinnamon is stealing?

https://github.com/user-attachments/assets/f1007400-ccaf-4d48-b67b-6066094bc1c4

**Comment by StefanSchippers** [comment]
I found this in Cinnamon. Is this true also if mouse is over an application window? this should be done only when hovering over a free desktop area...
![1](https://github.com/user-attachments/assets/4d267783-628b-4e74-a3ea-d6887b3c66ea)

**Comment by olisnr** [comment]
cntr-f is normally for searching. cinnamon dont steal this. its used in many different SWs. the search-dialog opens also in Xschem. and the zooming the full graph is also working on my other cinnamon computer. 
but on this one i use now its not... i will install Xschem again, and tell You the result...

**Comment by olisnr** [comment]
after reinstalling its working! thanks a lot for all Your work!
