### ISSUE TITLE
Improved synchronization of plots

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#245]
Hello!
Thank you for ability to define individual cursors, it is very neat feature.
It would be great to have ability to have individual synchronization between graphs.  
Let me explain:
for example, we have 4 graphs, and in that case, we can make 1 and 2 graphs synchronized, and 3 and 4 synchronized, without synchronization between 1 (2) and 3 (4). I would imagine it like an additional menu in graph's options, where we can set list of graphs that should be synchronized...
Thank you in advance, George.

**Comment by StefanSchippers** [comment]
You can do something like that by "unlocking" graphs and selecting a subset of them before zooming / moving / panning.

https://github.com/user-attachments/assets/abaf1744-49be-4410-bd8c-3130bc4245bb
