### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by trongcuhp** [StefanSchippers/xschem#247]
![image](https://github.com/user-attachments/assets/4227986a-a8f7-48c2-b3ca-349436afe408)
i met the error, and i dont know what does it mean

**Comment by StefanSchippers** [comment]
Can you add some context? 
- What was the operation that triggered the error? 
- Can you repeat again the error?
- What is the system you are using ? (Linux, Windows, Windows + Linux in WSL, Virtualmachine, ...)

The error is from TCL.
If I can reproduce the problem I can fix it.

**Comment by StefanSchippers** [comment]
Closed. No feedback
