### ISSUE TITLE
Font issue in Tk frame

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#249]
Hello!
How to fix this?
![image](https://github.com/user-attachments/assets/0d569fa5-26fc-42ee-b6e9-b2f2692b6098)
Cairo is installed, issue is in tk elements only, thank you!

**Comment by StefanSchippers** [comment]
Sorry, what is exactly the problem?

**Comment by georgtree** [comment]
Absence of antialising

**Comment by StefanSchippers** [comment]
what is the tcl-tk version you are using to build xschem?

**Comment by georgtree** [comment]
9.0

**Comment by StefanSchippers** [comment]
On a windows machine or on a Linux system? (real or emulated, doesnt matter)

**Comment by georgtree** [comment]
Fresh kubuntu 24lts, I reinstall the system today and build xschem

**Comment by StefanSchippers** [comment]
ensure font packages are installed:
**fonts-freefont-ttf  fontconfig fonts-liberation2 fonts-liberation fonts-dejavu**.

You can check if the font issue is generic with tk 9.0: 
start the `wish9.0` shell, write these commands in it:
```
% button .a -text abcdefghijkABCDEFGHIJK
.a
% pack .a
```

do you see the same non aliased characters in the button?

![1](https://github.com/user-attachments/assets/af5c193a-1819-4512-be3f-f3fc1cbb97ea)

**Comment by StefanSchippers** [comment]
Also at the xschem prompt issue this command to check if xft is used. (xft = X FreeType interface)

```
% ::tk::pkgconfig get fontsystem
xft
% 
```

If you don't get 'xft' then tcl-tk is using a bitmap font system and you probably need to change some font configuration file in your home directory (in ~/.config or other places).

**Comment by georgtree** [comment]
I installed all fonts, and run ::tk::pkgconfig get fontsystem, the result is x11

**Comment by georgtree** [comment]
Ok i checked configure log for Tk, and found this:
checking whether to use xft... no
need to find why it doesn't detect it

**Comment by StefanSchippers** [comment]
Yes I was writing this: install **libxft-dev**
Good!
