### ISSUE TITLE
Ability to disable/move graph legend

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#250]
Hello!
it would be great to have an ability to turn off the legend for the graph, it becomes messy when there a lot of plots are on the same graph. Or maybe make an ability to move it/change font size. The other possibility I can see is to make similar to symbols text: we hide legend and then make a link in text block to the particular graph.
Thank you in advance!

**Comment by StefanSchippers** [comment]
Added a 'Legend' checkbutton in graph dialog box.
there is also an option to use `alias;node` instead of `node` in the signal list. If alias is a very short name more nodes can be accomodated in legend. See image.
![1](https://github.com/user-attachments/assets/dd74affa-f209-427c-ab5c-72a2506b6c0e)
