### ISSUE TITLE
Add constants qualificator in graph drop-down menu

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#251]
Hello!
I found that there is no word constants in drop-down menu here:
![image](https://github.com/user-attachments/assets/e6e55031-8380-4957-99c7-0ba599b73326)

**Comment by StefanSchippers** [comment]
I will add the constants menu.
In the mean time you can write it in the dropdown textbox menu. 
![1](https://github.com/user-attachments/assets/6849dbdc-e2ed-45fb-b7bb-ed30bf8901bd)

**Comment by georgtree** [comment]
Hello!
This updates broke how it works previously, now constants always reads as complex, and shows strange things when try to plot. I used constants for reading data that were extracted with .meas statement as vectors in raw file.

**Comment by StefanSchippers** [comment]
Do you have an example raw file to send me for inspection?
If the ngspice convention is to store complex data in the "Constants" section I must read as complex data.
If there are also "Complex" sections with real data I must handle this.

**Comment by georgtree** [comment]
Previously it was shown like it:
![image](https://github.com/user-attachments/assets/166e8610-9d9a-4560-85c0-d837265327a5)

**Comment by StefanSchippers** [comment]
Thank you, your raw file explains the issue. ngspice can save both real and complex "constants" sections:


```
Title: Constant values
Date: Tue Oct  8 15:02:40 UTC 2024
Command: ngspice-43+, Build Tue Oct  8 15:02:40 UTC 2024
Plotname: constants
Flags: complex
No. Variables: 12
No. Points: 1

```


```
Title: Constant values
Date: Wed Feb 14 13:10:01 UTC 2024
Plotname: constants
Flags: real
No. Variables: 5
No. Points: 5

```

Ok, understood, will fix that. Will look at the **Flags** line instead of assuming a data type.

**Comment by StefanSchippers** [comment]
Ok above fix is done. If you have a chance please test.

**Comment by georgtree** [comment]
Just checked, it works well, thank you!
