### ISSUE TITLE
Using the Sky130 technology alongside a power MOSFET model

### ISSUE THREAD

**Issue by AranweLTT** [StefanSchippers/xschem#254]
Issue: I am using Xschem with NGSpice to perform analog simulations involving power MOSFETs. Specifically, I want to simulate circuits using the Sky130 technology alongside a power MOSFET model.

Current Situation:
- I can successfully simulate Sky130 technology using HSpice compatibility mode.
- I can also simulate power electronics using PSpice compatibility mode.
- However, I am unable to simulate both together due to compatibility mode conflicts.

Attempts:
I tried translating an existing model from LTSpice to NGSpice by adjusting the IF syntax, behavioral sources etc. While this sometimes works, it often results in significant convergence issues, and strange behavior in general (possibly due to translation errors or other limitations).

Questions:
- Is there an easy solution I'm unaware of which allows for just a specific library to loaded with a different compatibility mode?
- Is it possible to configure Sky130 to use PSpice compatibility mode instead of HSpice?
- Do you have any recommendations for dealing with convergence issues when combining these models?
- Would looking into Xyce offer any advantages ? (I haven't yet due to the complexity of the install...)

Here is my attempt at adapting a model from Wolfspeed (this one specifically because it doesn't contain any tables which makes it a little easier to begin with):
[CPM3-1200-0013A-original.txt](https://github.com/user-attachments/files/17958924/CPM3-1200-0013A-original.txt)
[CPM3-1200-0013A-spice3.txt](https://github.com/user-attachments/files/17958997/CPM3-1200-0013A-spice3.txt)

Any guidance on best practices for model translation or configuration adjustments would be greatly appreciated.
Thank you for your assistance!

**Comment by StefanSchippers** [comment]
This is very simulator specific. You should ask to the ngspice developers [here](https://sourceforge.net/p/ngspice/_list/tickets). Either file a ticket (bug or feature request) of add a post in the discussion tab.
