### ISSUE TITLE
question to the cntr-modifier and graph-dialog

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#255]
the cntr-modifier is used to deselect selected things in Lclick, but also to trigger launchers. while modifies selecting via rectangle to a drag mode.
may be it would be clearer if:

cntr-Lclick selects in drag-mode (partial line points)
cntr-rect selects in drag-mode
Lclick selects in move-mode (all line points)
rect selects in move-mode
shift Lclick toggles selection (if add in move mode)
shift rect toggles selection (if add in move mode)
cntr shift Lclick toggles selection (if add in drag mode)
cntr shift rect toggles selection (if add in drag mode)
l launsches the current selected launcher... or something similar
what do You think?

the graph dialog is sometimes a bit strange, as example if i use `i()` without `"`:

![gd](https://github.com/user-attachments/assets/d732d2d7-64b5-44e5-b676-10b9f472fd98)

would it be possible to include the `"`, so that its not needed anymore (also for calculations)?

**Comment by StefanSchippers** [comment]
Deselection is done with Alt+LClick, so it is different from Ctrl-LClick.
The only problem with this is on Macs as they don't have the Alt key (they have the Command key).
But in xschem the Windows key can also be used instead of the Alt key, and to my knowledge the Mac Command key is mapped the same as the  PC Windows key.

**Comment by olisnr** [comment]
for multi-line there is the `\`.

**Comment by olisnr** [comment]
> Deselection is done with Alt+LClick, so it is different from Ctrl-LClick. The only problem with this is on Macs as they don't have the Alt key (they have the Command key). But in xschem the Windows key can also be used instead of the Alt key, and to my knowledge the Mac Command key is mapped the same as the PC Windows key.

yes `cntr` is the way of KLayout to deselect... :) but cntr Lclick would really be nice for the drag-selection...

**Comment by StefanSchippers** [comment]
It is now possible to enter wave expressions on one line with spaces without requiring double quotes.
quotes are allowed and are necessary if you want to span a wave expression on multiple lines (this is useful if expression is very long). The backslash for line continuation was too difficult to implement considering that xschem applies color tagging to wave names/expressions in the graph dialog box, so for multiple lines use "..."

Please do some tests.

**There is one side effect:**
In some graphs I used to write signal lists like:
RST DATA CLK
This does not work any more, you have to put these on different lines:
RST
DATA
CLK


Thank you

**Comment by olisnr** [comment]
is it possible, that the change makes TCL code different?
i used to have lines like:
`diff0;i(vsingle_all)%[rawfilestart]_temp_mosff.spice.raw
`
in `""` and now its not working anymore. i will try to get it work, but probably You know already how it actual works :)

**Comment by olisnr** [comment]
the `""` free graph-dialog is working perfect for me. much nicer. and i think You also improved the text-dialog much. i can undo and redo, thats new, or not?

thanks a lot!
