### ISSUE TITLE
Create raw file from arbitrary data

### ISSUE THREAD

**Issue by georgtree** [StefanSchippers/xschem#258]
Hello!
There is a way to create raw file with command `xschem raw new name type sweepvar start end step`, also we can add new vectors to existing raw file, or modify existent  ones. But, is there  a way to create raw file from arbitrary data, for example something like:
`xschem raw new rawName sweepvarName $sweepvarData vector1Name $vector1Data ...` ?
It would be great to see this ability in xschem, thank you.

**Comment by StefanSchippers** [comment]
There are various ways.
One is to read data formatted as an ascii table:

```
X     Y     Z
0     0     0
1     1     1
2     4     8
3     9    27
4    16    64
5    25   125     
```
The first line provide the vector names, the first column is the x axis, 
all other columns are data to be plotted. Lines beginning with '#' are ignored, 
double empty lines start a new dataset (a new line, disjoint from previous)
single empty lines are ignored.
If above lines are saved in a file named 'table1' the command to read the table in xschem is:

`xschem raw table_read table1`

you can then plot the data as usual:

![2](https://github.com/user-attachments/assets/7fb7683f-15c0-4ab1-aef7-e1d27b52a3b5)

The second method is to create data in memory:

`xschem raw new test test1 x -10 10 0.01`

Creates a new plot test1, from in-memory data 'test' (you can have many plots by changing their names)
with X-axis range form -10 to 10 and 0.01 step. 
A 2001 element 'x' vector is created. {-10, -9.99, .... , 0, ..., 9.99, 10}

`xschem raw add y { x x * -1 * exp() }`

Adds a 'y' variable equal to exp(-x^2).

![2](https://github.com/user-attachments/assets/41696316-62f3-41a1-9a38-3df4bd519c47)

This command: 

`for {set i 900} {$i < 1100} {incr i} { xschem raw set y $i 1 }`

Pokes into the data and changes part of the gaussian to a box.

![2](https://github.com/user-attachments/assets/ce60d228-2ee4-4f6a-8ecb-871119406f02)

You can also do something like this:

```
xschem raw new test test1 x 0 3 1 ;# create a 4 item x vector (0,1,2,3)
xschem raw add y ;# add an y variable (all zero, (0,0,0,0)
# fill x and y with new data
for {set i 0} {$i < 4} { incr i} {
  xschem raw set x $i [expr $i/10.]
  xschem raw set y $i [expr exp($i)]
}
```
![1](https://github.com/user-attachments/assets/ed8bfe3c-211d-4712-b097-d2129b162afd)


the attached example loads a table with measured power [kW] vs speed [km/h] for some different car types.

![1](https://github.com/user-attachments/assets/a9281bd6-e012-4aaf-8798-773385d31321)


[power_vs_speed_cars.zip](https://github.com/user-attachments/files/18201755/power_vs_speed_cars.zip)

**Comment by georgtree** [comment]
Got it, thank you very much :)
