### ISSUE TITLE
Possible bug in wiring

### ISSUE THREAD

**Issue by ananthchellappa** [StefanSchippers/xschem#259]
Is it possible the code could be improved? It's adding solder dots incorrectly and in some cases, it hasn't registered the connection for one wire..
![demo_Xschem_wiring](https://github.com/user-attachments/assets/0de9b94b-c539-4367-8c79-1ba19fc50c7c)

**Comment by StefanSchippers** [comment]
This is not a bug
partially overlapped wires will show dots, see figure.
![1](https://github.com/user-attachments/assets/add1d893-fde3-4f46-9dd5-adb1e8af95de)

partially overlapped wires can be merged with the '&' command (`Tools -> Join.Trim wires`)
this operation can be made the default with `Options-> Auto Join/Trim wires` or by setting 
`set autotrim_wires 1` in the xschemrc file. If AutoTrim is enabled behavior is pretty much the same as Cadence.

The "unmerged wires" behavior is sometimes desired, so xschem does not automatically merge wires if we want to keep all the pieces separate. In below image I can select the piece of wire, delete it and insert a current meter. Of course there are multiple ways to do this task, but this is just a user option.
![1](https://github.com/user-attachments/assets/206151ad-7249-43e4-a36d-b09cf75446ec)

**Comment by StefanSchippers** [comment]
But yes, I see some connecting dots added whie doing Undo.This is a bug. Will look into that.

**Comment by StefanSchippers** [comment]
The bug you found is hopefully fixed. (connecting dots appearing on unrelated wires when doing an Undo)
If you have a chance to do some tests let me know if you find other inconsistencies related to connecting dots (not related to overlapping wires, which is known and not a bug (use auto Trim/Join for that).

**Comment by ananthchellappa** [comment]
I'll check Stefan. I'm looking into the docs.

Is it easy to update Xschem using an apt install command?

Thank you,
Ananth

**Comment by ananthchellappa** [comment]
I used git clone and then configure/make and I am not able to reproduce this issue, suggesting that it's fixed.

However, it may be worth nothing that I see this in the xterm from which the local (not /usr/local/bin/xschem) was launched:

```
ttuser@ubuntu-desktop:~/Downloads/xschem-src$ src/xschem 
Sourcing /usr/local/share/xschem/xschemrc init file
Sourcing /home/ttuser/.xschem/xschemrc init file
can't read "graph_use_ctrl_key": no such variable
xschem [~/Downloads/xschem-src] can't read "graph_use_ctrl_key": no such variable
can't read "graph_use_ctrl_key": no such variable
can't read "graph_use_ctrl_key": no such variable
can't read "graph_use_ctrl_key": no such variable
can't read "graph_use_ctrl_key": no such variable

can't read "graph_use_ctrl_key": no such variable
can't read "select_touch": no such variable
can't read "graph_use_ctrl_key": no such variable
can't read "select_touch": no such variable
can't read "graph_use_ctrl_key": no such variable
```

**Comment by olisnr** [comment]
> I'll check Stefan. I'm looking into the docs.
> 
> Is it easy to update Xschem using an apt install command?
> 
> Thank you, Ananth

apt is very slow and behind. i would suggest You to download a zip from https://github.com/StefanSchippers/xschem/archive/refs/heads/master.zip
and install from source (in a terminal @ */xschem-master).
./cofigure
make -j7
sudo make install

http://repo.hu/projects/xschem/xschem_man/install_xschem.html tells You what You need to install before. if You did it once, its easy

**Comment by StefanSchippers** [comment]
As @olisnr pointed out it takes months to get a new release packaged into linux distributions.
To incorporate these very new changes either take the master tar.gz file or clone the xschem github repo. [Building compiling and installing](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html) is not dfficult, once you have the required libraries and dependencies installed.

**Comment by ananthchellappa** [comment]
No issue in latest release. Thanks for fixing.

Will request that wire command stay in "command" mode till ESC is pressed - so user an draw a multiple-segment-wire without clicking W each time for a new wire command. Cadence-style routing will come eventually 😊

**Comment by olisnr** [comment]
@ananthchellappa try `double left click` to end the track. then You dont need to `w` again :)
