### ISSUE TITLE
[Fixed] Minor UI bug: `rectangle_zoom()` seemingly zooms to infinity, without any straightforward way to zoom-out

### ISSUE THREAD

**Issue by TheSUPERCD** [StefanSchippers/xschem#262]
## HOW TO REPLICATE THE ISSUE
When zooming in by drawing a rectangle (by pressing the 'z' key and dragging the cursor), if the area enclosed by the rectangle is zero - meaning, when the drawn rectangle becomes a line or a point, the resulting zoom magnifies everything to infinity (or at least it seems like it does), making the process of zooming out nearly impossible, except for using the 'F' key to reset the zoom back to normal. 

I do not think that this was the intended way for the software to behave, and it seemed like an annoying issue to face when trying to work on a large enough digital circuit network. The demonstration of how the bug behaves is shown in the following attachment.

https://github.com/user-attachments/assets/18ae6006-2dd2-4e87-a780-c4f47e59ca2e

**Comment by StefanSchippers** [comment]
Yes, you are right. Next commit will fix that. If no minimum  area is given no zoom will be done.
