### ISSUE TITLE
Warnings when compiling xschem

### ISSUE THREAD

**Issue by ghost** [StefanSchippers/xschem#27]
Hi. Today I was following the [video](https://youtu.be/jXmmxO8WG8s) of Stefan and the documentation for installing xschem.
All the [packages required](http://repo.hu/projects/xschem/xschem_man/install_xschem.html) were installed previously. 
Then I chose my custom installation path as my home using `./configure --prefix=/home/nelson`
All output checks were ok.
But, when I run `make` I get these warnings:
```cpp
netlist.c:1135:15: warning: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1135 |               fscanf(fd, "%d",&tmpi);

psprint.c:712:7: warning: format not a string literal and no format arguments [-Wformat-security]
  712 |       fprintf(fd, utf8_enc[i]);
      |       ^~~~~~~
psprint.c:715:7: warning: format not a string literal and no format arguments [-Wformat-security]
  715 |       fprintf(fd, utf8[i]);

hilight.c:166:13: warning: format not a string literal and no format arguments [-Wformat-security]
  166 |             fprintf(fd, str);
      |             ^~~~~~~
hilight.c:195:5: warning: format not a string literal and no format arguments [-Wformat-security]
  195 |     fprintf(fd, str);
      |     ^~~~~~~

rawtovcd.c:86:5: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   86 |     fread(values[p], sizeof(double), nvars, fd);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I read from another issue that these warnings don't care.
Then I run `make install` and everything ok.
But, when I want to run `xschem` command, it doesn't exist.
What do I have to do to fix this?

**Comment by StefanSchippers** [comment]
In some cases you need to type 'rehash' in the terminal to see new commands appear...
