### ISSUE TITLE
Spice Netlisting | False Warnings | Undriven and Open Nets

### ISSUE THREAD

**Issue by rowhit** [StefanSchippers/xschem#32]
I am not sure why I am getting following warnings when netlisting for spice. I have created a simple schematic to a xyce comparator model. I keep getting the following netlisting error, despite the fact that netlist compiles and runs fine. Is there a way to turn off these warnings?

![image](https://user-images.githubusercontent.com/4926941/142775299-8575d3f0-ad0b-40de-ac5a-dbaa7050732d.png)

Here is the comp symbol and verilogA port definition:
![image](https://user-images.githubusercontent.com/4926941/142775360-8b183a03-2d8c-4749-8976-7030b46a7793.png)
![image](https://user-images.githubusercontent.com/4926941/142775398-2406c601-3754-4e2e-b860-65a32790a761.png)

**Comment by StefanSchippers** [comment]
These are just warnings, however this is intended.  in a schematic any net should be either driven by another block `out` or `inout` pin or have a `devices/ipin.sym` or `devices/iopin.sym` component.
Moreover an output net should go somewhere, if a net is driven by a block and goes nowere a warning is printed.
In top level testbenches you often don't want to put input pins or output pins, to clear these warnings just add a `devices/noconn.sym` component to the nets (see picture).This makes it clear that the net is not a float and it is designer intention to drive this net with the testbench.
Anyway these are just warnings, netlist will be correct anyway.

Please also check the symbol pins, (hit '1' on the red squares),  the 'out' pin should have 'dir=out' or 'dir=inout', while other pins should have 'dir=in".

I do not understand the 'Open net: out' message, i can not replicate such a situation. Can you please verify if the capacitor is correctly placed and connected to the 'out' node (for example: it is not placed off-grid) , and the 'dir' attribute of the top capacitor pin (and the 'dir' attr of the comparator out node)?

Check also that schematic pin names and directions match symbol.
![1](https://user-images.githubusercontent.com/69359491/142783916-c9ca4670-f301-42b0-ad96-af3c70db9b9c.png)
