### ISSUE TITLE
Regarding extending pin with same net name

### ISSUE THREAD

**Issue by ratul619** [StefanSchippers/xschem#34]
Hi ,

I am doing a hierarhical symbol. So when i instantiate a symbol , whose pins are lets say A,Vdd,Gnd.-- is there any shortcut or option so that with single key the pins spreads out (wire) with same net name ? 

Thanks!

**Comment by StefanSchippers** [comment]
yes, the key is 'H' or menu 'Symbol->Attach pins to component instance'. 
see also the manual page: http://repo.hu/projects/xschem/xschem_man/creating_schematic.html
the paragraph 'Automatic Component Wiring'
