### ISSUE TITLE
Create LVS netlist from command line

### ISSUE THREAD

**Issue by hpretl** [StefanSchippers/xschem#37]
I would like to create an LVS netlist from the command line. Currently I use

`xschem -n -s -q --no_x $CELL_SCH -N $NETLIST_SCH`

to write the netlist, but I would like to have the `.subckt` in the file? Is there an option to do this? In the GUI there is the "LVS netlist" option.

**Comment by StefanSchippers** [comment]
Yes this can be done. There is no specific command line option, but there is a tcl variable, and it can be set with --tcl:
`xschem -n -s -q --no_x  --tcl 'set top_subckt 1'  $CELL_SCH -N $NETLIST_SCH`

The --tcl '...' can be used to change (almost) any variable that you have in the xschemrc file.

**Comment by hpretl** [comment]
Perfect, works. Thanks!
