### ISSUE TITLE
Connect 2 net segments have same name 

### ISSUE THREAD

**Issue by vietnh89** [StefanSchippers/xschem#44]
Hi Stefan,
Does the tool support to connect 2 net segments which assigned same label? I attached a sample picture, P_PWS_N segments are 1 net.
![image](https://user-images.githubusercontent.com/97084707/148084400-649fa54c-5be7-4e46-b386-f432f0c48d4c.png)

**Comment by StefanSchippers** [comment]
Sure! LDQ_B in following picture is  one single net,

You need to attach a label to the net. As long as labels have the same name it is considered a single net.
the label symbol is called `lab_wire.sym` or `lab_pin.sym` in the devices` component directory of xschem.

see [this manual page](https://xschem.sourceforge.io/stefan/xschem_man/creating_schematic.html) for details on how to attach a label to a net.
 
![1](https://user-images.githubusercontent.com/69359491/148196962-ca0bb45a-1de6-4c18-87d5-760751639448.png)

**Comment by vietnh89** [comment]
Thanks
