### ISSUE TITLE
Problem when configuring

### ISSUE THREAD

**Issue by zhengshuaige66** [StefanSchippers/xschem#48]
Hi Stefan,
       When configure xschem, an error code appeared “Node libs/script/tk/* is required but provided detection callback fails to find that feature on that system.” But I have installed libtcl8.6(8.6.11+dfsg-1)，libtk8.6(8.6.11-2build1) and tk8.6/tcl8.6(8.6.11+1build1) .
       Thank you.

![image](https://user-images.githubusercontent.com/52859848/155927525-fc49837c-f334-45ae-920a-268ef17d6646.png)

**Comment by StefanSchippers** [comment]
you probably need to install tk8.6-dev and tcl8.6-dev packages:
sudo apt-get install tcl8.6-dev tk8.6-dev. Then run configure again.
Also see complete list of required libraries [here](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).
Let me know if something else does not work.

**Comment by zhengshuaige66** [comment]
I checked the library and it looks like the required library is indeed installed.

> <img width="347" alt="Snipaste_2022-03-01_11-17-54" src="https://user-images.githubusercontent.com/52859848/156099004-adc2baa3-299f-4d26-9183-5ca2ca8fa0c8.png">

> <img width="312" alt="Snipaste_2022-03-01_11-18-52" src="https://user-images.githubusercontent.com/52859848/156099071-a3c54a3a-4dfe-499d-9ea8-07399d7a89f4.png">

I observed the information in other people's issues and found the following differences.

> <img width="518" alt="Snipaste_2022-03-01_11-19-19" src="https://user-images.githubusercontent.com/52859848/156099410-4330befc-4660-494d-8edd-8b9b836c1d03.png">

> <img width="498" alt="Snipaste_2022-03-01_11-23-02" src="https://user-images.githubusercontent.com/52859848/156099447-96ce948f-2bcf-4cef-8a70-ba8e6e437457.png">

This looks like it found tk8.6 but can't locate it

**Comment by zhengshuaige66** [comment]
Stefan,
     Thank u very much. I downloaded the latest installation package from the tk/tcl official website for installation(both tk and tcl need to be installed), and now I can install xschem normally.
