### ISSUE TITLE
Document xschem tcl command extensions and config variables in developer section of manual.

### ISSUE THREAD

**Issue by StefanSchippers** [StefanSchippers/xschem#59]

**Comment by rafmag** [comment]
First of all, I'm very impressed with XSCHEM. Coming over from some other eda tools, I have found I can do almost everything I'm used to doing in those tools. I'm trying to evaluate the ability to use XSCHEM together with XYCE and some other tools to go through a full IC design process. 

That being said, how is this going? There have been a couple of "nice to have features" I would like. I think I'm able to code them myself but would need some documentation on the xschem TCL command list.

**Comment by StefanSchippers** [comment]
Done. https://xschem.sourceforge.io/stefan/xschem_man/developer_info.html#cmdref
