### ISSUE TITLE
Feature request: Double click to open object properties...

### ISSUE THREAD

**Issue by rafmag** [StefanSchippers/xschem#61]
Coming over from some other commercial EDA tools, it would me nice to be able to, for example, be able to double click on a resistor to change it's value.

**Comment by StefanSchippers** [comment]
This is now done. Can you please update your xschem from git and test?

**Comment by rafmag** [comment]
Will do. Thanks for the quick turnaround!

**Comment by rafmag** [comment]
Working Nicely. Thanks!
