### ISSUE TITLE
xpm in installed but while configuring it says not found.

### ISSUE THREAD

**Issue by ombhilare999** [StefanSchippers/xschem#8]
Hi @StefanSchippers, I was trying to install xschem.
Following the manual on xschem site:
> http://repo.hu/projects/xschem/xschem_man/install_xschem.html
But I got this error, kindly help
Thank you
![image](https://user-images.githubusercontent.com/40693854/110203707-a9448900-7e95-11eb-8858-b7669b886889.png)

**Comment by ombhilare999** [comment]
I figured out the issue
libxpm was missing.
Thank you

**Comment by StefanSchippers** [comment]
Thank you for closing the issue, i came here too late, but happy you were able to get xschem build.
Yes, libxpm (or libxpm4 on some systems) as well as libxpm-dev (for header files) is listed in the depenciences on the 'install xschem' page.
Regards,

**Comment by Magaspa** [comment]
> Hi @StefanSchippers, I was trying to install xschem. Following the manual on xschem site:
> 
> > http://repo.hu/projects/xschem/xschem_man/install_xschem.html
> > But I got this error, kindly help
> > Thank you
> > ![image](https://user-images.githubusercontent.com/40693854/110203707-a9448900-7e95-11eb-8858-b7669b886889.png)

Can you tell me how to fix it?
