### ISSUE TITLE
Unable to use ./configure command

### ISSUE THREAD

**Issue by satvikgoel950** [StefanSchippers/xschem#81]
after cloning the repo when i use ./configure it says
no directories found 
./conifgure 4 not found
I have installed all the libraries in the manual but still i face same error
what could be possible wrong please help

**Comment by StefanSchippers** [comment]
Try to delete the cloned repository and repeat:
The steps are: 
```
git clone https://github.com/StefanSchippers/xschem xschem_git
cd xschem_git
./configure
make
sudo make install

```
Don't do any following steps if previous fails.

If this fails, please send me the file `xschem_git/scconfig/config.log`

**Comment by satvikgoel950** [comment]
Thanks for replying, I have tried cloning again but no luck. Also in the folder told by you there is no config.log file. Attaching a screenshot of same.
![Screenshot (211)](https://user-images.githubusercontent.com/60666893/188262255-c511d64b-0294-4b37-9d54-d6439f1bebd8.png)

**Comment by StefanSchippers** [comment]
Please send me a listing of the xschem_git directory and a screenshot of the result of the ./configure command.

**Comment by satvikgoel950** [comment]
Here they are.
![Screenshot (212)](https://user-images.githubusercontent.com/60666893/188262414-23c7b246-c8b9-4220-b40d-a1b6e1d7085d.png)
![Screenshot (213)](https://user-images.githubusercontent.com/60666893/188262416-e318b675-6824-4929-8763-aca6c2261567.png)

**Comment by StefanSchippers** [comment]
Ok, this is simple. You don't have a C compiler installed on the system. Install `gcc` package and also `make`, in case you don't have it already.

**Comment by satvikgoel950** [comment]
But they are already installed. heres a screenshot
![Screenshot (214)](https://user-images.githubusercontent.com/60666893/188262556-1981f446-d1ed-4805-afc3-f3f08836f691.png)

**Comment by StefanSchippers** [comment]
Ok, your system does not have a cc symlink to gcc, so try this:

./configure --CC=gcc

**Comment by satvikgoel950** [comment]
same error
![Screenshot (215)](https://user-images.githubusercontent.com/60666893/188263378-a96037d7-9d9f-479b-894f-ca04c127d17f.png)

**Comment by StefanSchippers** [comment]
Oh yes, you need to have CC defined even before building configure itself.
Do this:
```
export CC=gcc
./configure
```

**Comment by satvikgoel950** [comment]
same error again
![Screenshot (216)](https://user-images.githubusercontent.com/60666893/188263533-33fb74d4-1e11-4995-bdf1-fa4a840a9cc1.png)

**Comment by StefanSchippers** [comment]
ok do these commands.
echo $PATH
which gcc
which cc
and send the results as text, don't do screenshots
also do: 
 ./configure >log 2>&1 
 and send me the log file (no screenshots)
 
 Thank you very much for reporting

**Comment by satvikgoel950** [comment]
satvik@satvik:~/xschem_git$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
satvik@satvik:~/xschem_git$ 
satvik@satvik:~/xschem_git$ which gcc
satvik@satvik:~/xschem_git$ which cc
satvik@satvik:~/xschem_git$

**Comment by StefanSchippers** [comment]
send the log file of `./configure >log 2>&1`

**Comment by satvikgoel950** [comment]
these are the contents of log2 file
gcc -DGENCALL -DRUNTIME -g  -DPLUGIN_SCRIPTS   -Isrc//tmpasm  -DPLUGIN_PARSGEN    -DPLUGIN_GUI     -Isrc//default   -c -o hooks.o hooks.c

file in not supported to upload

**Comment by StefanSchippers** [comment]
there should not be a log2 file, there is a space after log, so please try again the above command:
./configure >log 2>&1

You will have a 'log' file.

**Comment by satvikgoel950** [comment]
gcc -DGENCALL -DRUNTIME -g  -DPLUGIN_SCRIPTS   -Isrc//tmpasm  -DPLUGIN_PARSGEN    -DPLUGIN_GUI     -Isrc//default   -c -o hooks.o hooks.c
make: gcc: No such file or directory
make: *** [<builtin>: hooks.o] Error 127
./configure: 4: ./configure: not found

**Comment by satvikgoel950** [comment]
yes these are the content unable to upload the log file

**Comment by StefanSchippers** [comment]
ok thanks for now

**Comment by StefanSchippers** [comment]
ok i am asking to more ubuntu users, 
can you please paste here (as text) the output of following command? 
Please close the terminal and open a new one , xince the export CC we did before must go away.
`update-alternatives --display cc`

**Comment by satvikgoel950** [comment]
here,
satvik@satvik:~$ update-alternatives --display cc
update-alternatives: warning: alternative /usr/bin/gcc (part of link group cc) doesn't exist; removing from list of alternatives
cc - auto mode
  link best version not available
  link currently points to /usr/bin/gcc
  link cc is /usr/bin/cc
  slave cc.1.gz is /usr/share/man/man1/cc.1.gz
satvik@satvik:~$

**Comment by StefanSchippers** [comment]
can you also do (copy and paste below text in a terminal):
dpkg -l |grep gcc

**Comment by satvikgoel950** [comment]
atvik@satvik:~$ dpkg -l |grep gcc
ii  gcc                                        4:11.2.0-1ubuntu1                       amd64        GNU C compiler
ii  gcc-11                                     11.2.0-19ubuntu1                        amd64        GNU C compiler
ii  gcc-11-base:amd64                          11.2.0-19ubuntu1                        amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-base:amd64                          12-20220319-1ubuntu1                    amd64        GCC, the GNU Compiler Collection (base package)
ii  libgcc-11-dev:amd64                        11.2.0-19ubuntu1                        amd64        GCC support library (development files)
ii  libgcc-s1:amd64                            12-20220319-1ubuntu1                    amd64        GCC support library
ii  libuno-cppuhelpergcc3-3                    1:7.3.5-0ubuntu0.22.04.1                amd64        LibreOffice UNO runtime environment -- CPPU helper library
ii  libuno-purpenvhelpergcc3-3                 1:7.3.5-0ubuntu0.22.04.1                amd64        LibreOffice UNO runtime environment -- "purpose environment" helper
ii  libuno-salhelpergcc3-3                     1:7.3.5-0ubuntu0.22.04.1                amd64        LibreOffice UNO runtime environment -- SAL helpers for C++ library
satvik@satvik:~$

**Comment by StefanSchippers** [comment]
Thank you for your patience
So it appears your system *thinks* gcc is installed and it was installed but /usr/bin/gcc is not there, for some reason installation is broken. Try to force-reinstall gcc and make:
`sudo apt-get install --reinstall gcc make`

**Comment by satvikgoel950** [comment]
Thank you so much sir it worked.

**Comment by StefanSchippers** [comment]
for some reason gcc was not installed correctly during ubuntu installation. You see how many weird problems may happen.

**Comment by StefanSchippers** [comment]
Ok if xschem was built with no problems please close this issue. If you ran in other related problems you can open a new issue of course.

**Comment by satvikgoel950** [comment]
yes. Thanks for the support.
