### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by abhisupa** [StefanSchippers/xschem#9]
Hi Stefan,
I am getting error while running make -j4
Please if you can help here

![image](https://user-images.githubusercontent.com/68303504/110245134-dbe29600-7f16-11eb-9c67-e43b02db6df4.png)

![image](https://user-images.githubusercontent.com/68303504/110245079-accc2480-7f16-11eb-9c95-4d89e7120388.png)

**Comment by StefanSchippers** [comment]
You probably did run:
` ./configure ....--prefix=/home/schippes` .
schippes is my username on my system. You need to use your username, like: 
`./configure --prefix=/home/abhishek`

you can also run ./configure  with no prefix, this will install xschem in `/usr/local/bin` and xschem support files in `/usr/local/share`.
in this latter case you need to run make install with root privileges.
To solve the ussue do : 
```
make clean
./configure --prefix=/home/abhishek
make
make install
```

**Comment by abhisupa** [comment]
Yeah, I followed exactly word by word :). I still seeing the same issue as before after following 
make clean
"./configure --prefix=/home/abhishek
make
make install" 

![image](https://user-images.githubusercontent.com/68303504/110250384-e8271d00-7f2f-11eb-884c-38d752be55ea.png)

**Comment by StefanSchippers** [comment]
The messages shown above are only warnings, xschem does build fine. I will eventually fix xschem to remove these warnings (i do not get any warning on my system, but this depend on the compiler)

**Comment by abhisupa** [comment]
> The messages shown above are only warnings, xschem does build fine. I will eventually fix xschem to remove these warnings (i do not get any warning on my system, but this depend on the compiler)

Thanks Stefan, you are correct, I am able to run it now, Only difference from the video instruction to what I did is to run command 'sudo apt install xschem'. I thought that is not required once installed from git.
