### ISSUE TITLE
"can't find file to patch at input line 4"

### ISSUE THREAD

**Issue by realsurgent** [StefanSchippers/xschem#93]
Hi, when I ran `patch -p2`, I got the error below so I can't patch:

![HATA2](https://user-images.githubusercontent.com/56458329/199118419-6206788c-5452-49c2-ae46-d147bf3cd23f.png)

Please help me

**Comment by StefanSchippers** [comment]
Please follow [this page](https://xschem.sourceforge.io/stefan/xschem_man/tutorial_xschem_sky130.html) for skywater pdk instalation. You don't need any more to patch the google skywater pdk.
All the work is now done by open_pdks.

**Comment by realsurgent** [comment]
Okay, thank you!

**Comment by StefanSchippers** [comment]
you need to add a dot (.) at the end of the cp command. In unix '.' means 'here' that is , copy the specified file here.
