### ISSUE TITLE
Can't start xschem from desktop file when tcl-tclreadline package installed

### ISSUE THREAD

**Issue by erusyd** [StefanSchippers/xschem#96]
OS: Linux Mint 20.3 and 21.1
XSCHEM version: source from git

After installing tcl-tclreadline package from repository:
```
sudo apt install tcl-tclreadline
```
I can't start xschem from the following xschem.desktop file:
```
[Desktop Entry]
Type=Application
Icon=/usr/share/icons/xschem.xpm
Name=XSCHEM
Exec=xschem
Categories=Electronics;
```
If I remove tcl-tclreadline package, then xschem can be started from desktop file.

I can't figure out why this happens.

**Comment by StefanSchippers** [comment]
start xschem with the -b option. for info: xschem -h. also -r can be used to
 start without tclreadline...

Il Sab 14 Gen 2023, 14:49 Song Yadong ***@***.***> ha scritto:

**Comment by erusyd** [comment]
Thanks! It works now.
